import React, { createContext, useContext, useState } from 'react';

type Language = 'fr' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.catalog': 'Catalogue',
    'nav.rent': 'Louer',
    'nav.list': 'Proposer un outil',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    
    // Hero section
    'hero.title': 'Louez et partagez vos outils en toute simplicité',
    'hero.subtitle': 'La plateforme qui connecte les propriétaires d\'outils avec ceux qui en ont besoin. Particuliers et professionnels, trouvez l\'outil parfait près de chez vous.',
    'hero.search.placeholder': 'Rechercher un outil...',
    'hero.search.location': 'Localisation',
    'hero.search.button': 'Rechercher',
    
    // Categories
    'categories.title': 'Catégories populaires',
    'categories.garden': 'Jardinage',
    'categories.construction': 'Construction',
    'categories.automotive': 'Automobile',
    'categories.electric': 'Électrique',
    
    // Tools
    'tools.featured': 'Outils en vedette',
    'tools.day': 'jour',
    'tools.available': 'Disponible',
    'tools.rent': 'Louer',
    'tools.details': 'Voir détails',
    'tools.new_ad': 'Nouvelle annonce',
    'tools.my_ads': 'Mes annonces',
    'tools.edit': 'Modifier',
    'tools.view': 'Voir',
    'tools.delete': 'Supprimer',
    'tools.published': 'Publié',
    'tools.unpublished': 'Non publié',
    'tools.pending': 'En attente',
    'tools.approved': 'Approuvé',
    'tools.rejected': 'Rejeté',
    
    // Profile
    'profile.title': 'Mon Profil',
    'profile.profile': 'Profil',
    'profile.wallet': 'Portefeuille',
    'profile.requests': 'Demandes',
    'profile.reservations': 'Réservations',
    'profile.ads': 'Annonces',
    'profile.favorites': 'Favoris',
    'profile.edit': 'Modifier',
    'profile.save': 'Enregistrer',
    'profile.cancel': 'Annuler',
    'profile.verified': 'Vérifié',
    'profile.member_since': 'Membre depuis',
    'profile.individual': 'Particulier',
    'profile.company': 'Entreprise',
    'profile.delete_account': 'Supprimer mon compte',
    'profile.delete_confirm': 'Supprimer votre compte',
    'profile.delete_description': 'La suppression de votre compte est irréversible.',
    'profile.back_home': 'Retour à l\'accueil',
    
    // Forms
    'form.first_name': 'Prénom',
    'form.last_name': 'Nom',
    'form.email': 'Email',
    'form.phone': 'Téléphone',
    'form.address': 'Adresse',
    'form.country': 'Pays',
    'form.password': 'Mot de passe',
    'form.confirm_password': 'Confirmer le mot de passe',
    'form.title': 'Titre',
    'form.description': 'Description',
    'form.price': 'Prix',
    'form.category': 'Catégorie',
    'form.location': 'Localisation',
    
    // Actions
    'action.search': 'Rechercher',
    'action.filter': 'Filtrer',
    'action.sort': 'Trier',
    'action.save': 'Enregistrer',
    'action.cancel': 'Annuler',
    'action.confirm': 'Confirmer',
    'action.delete': 'Supprimer',
    'action.edit': 'Modifier',
    'action.view': 'Voir',
    'action.contact': 'Contacter',
    'action.close': 'Fermer',
    'action.back': 'Retour',
    'action.next': 'Suivant',
    'action.previous': 'Précédent',
    
    // Floating Action Button
    'fab.contact_support': 'Contacter le support',
    'fab.publish_ad': 'Publier une annonce',
    'fab.find_tool': 'Trouver mon outil',
    
    // Messages
    'message.success': 'Succès',
    'message.error': 'Erreur',
    'message.loading': 'Chargement...',
    'message.no_results': 'Aucun résultat trouvé',
    'message.confirm_delete': 'Êtes-vous sûr de vouloir supprimer ?',
    
    // Footer
    'footer.about': 'À propos',
    'footer.help': 'Aide',
    'footer.contact': 'Contact',
    'footer.legal': 'Mentions légales',
    'footer.rights': 'Tous droits réservés',
    'footer.cgu': 'CGU',
    'footer.privacy': 'Politique de confidentialité',
    'footer.faq': 'FAQ',
    
    // Login
    'login.title': 'Connexion',
    'login.subtitle': 'Connectez-vous à votre compte ToolShare',
    'login.email': 'Email',
    'login.password': 'Mot de passe',
    'login.signin': 'Se connecter',
    'login.no_account': 'Pas encore de compte ? S\'inscrire',
    'login.forgot_password': 'Mot de passe oublié ?',

    // Register
    'register.title': 'Inscription',
    'register.subtitle': 'Créez votre compte ToolShare',
    'register.user_type': 'Type d\'utilisateur',
    'register.individual': 'Particulier',
    'register.business': 'Entreprise',
    'register.first_name': 'Prénom',
    'register.last_name': 'Nom',
    'register.phone': 'Téléphone',
    'register.country': 'Pays',
    'register.address': 'Adresse',
    'register.address_help': 'Adresse complète avec code postal et ville',
    'register.password': 'Mot de passe',
    'register.confirm_password': 'Confirmer le mot de passe',
    'register.terms': 'J\'accepte les conditions d\'utilisation',
    'register.sales_conditions': 'J\'accepte les termes et conditions et les conditions de vente',
    'register.create_account': 'Créer mon compte',
    'register.have_account': 'Déjà un compte ? Se connecter',
    'register.select_country': 'Sélectionnez un pays',

    // About
    'about.title': 'À propos de Bricola',
    'about.subtitle': 'La plateforme de location d\'outils qui révolutionne le bricolage en connectant les propriétaires d\'outils avec ceux qui en ont besoin.',
    'about.mission_title': 'Notre Mission',
    'about.mission_1': 'Chez Bricola, nous croyons que chaque projet de bricolage mérite d\'avoir accès aux meilleurs outils, sans pour autant devoir les acheter.',
    'about.mission_2': 'Notre plateforme permet aux particuliers et professionnels de partager leurs outils inutilisés avec leur communauté locale, créant ainsi un écosystème durable et économique.',
    'about.mission_3': 'Nous facilitons l\'accès aux outils de qualité tout en favorisant l\'économie circulaire et les liens sociaux de proximité.',
    'about.values_title': 'Nos Valeurs',
    'about.community': 'Communauté',
    'about.community_desc': 'Créer des liens entre voisins et favoriser l\'entraide locale',
    'about.security': 'Sécurité',
    'about.security_desc': 'Garantir des transactions sécurisées et une assurance complète',
    'about.quality': 'Qualité',
    'about.quality_desc': 'S\'assurer que tous les outils respectent nos standards de qualité',
    'about.simplicity': 'Simplicité',
    'about.simplicity_desc': 'Rendre la location d\'outils aussi simple qu\'un clic',
    'about.stats_title': 'Bricola en chiffres',
    'about.tools_available': 'Outils disponibles',
    'about.active_users': 'Utilisateurs actifs',
    'about.cities_covered': 'Villes couvertes',
    'about.satisfaction': 'Satisfaction client',
    'about.team_title': 'Notre Équipe',

    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Une question, un problème ou simplement envie d\'échanger ? Notre équipe est là pour vous aider.',
    'contact.form_title': 'Envoyez-nous un message',
    'contact.first_name': 'Prénom',
    'contact.last_name': 'Nom',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le message',
    'contact.email_title': 'Email',
    'contact.phone_title': 'Téléphone',
    'contact.address_title': 'Adresse',
    'contact.hours_title': 'Horaires',
    'contact.hours_weekdays': 'Lundi - Vendredi : 9h00 - 18h00',
    'contact.hours_saturday': 'Samedi : 10h00 - 16h00',
    'contact.hours_sunday': 'Dimanche : Fermé',
    'contact.faq_title': 'Questions fréquentes',
    'contact.how_to_rent': 'Comment louer un outil ?',
    'contact.how_to_rent_answer': 'Recherchez l\'outil souhaité, sélectionnez les dates de location, et confirmez votre réservation. C\'est aussi simple que ça !',
    'contact.problem': 'Que faire en cas de problème ?',
    'contact.problem_answer': 'Contactez-nous immédiatement via notre support client. Nous sommes là pour résoudre tous vos problèmes rapidement.',
    'contact.how_to_list': 'Comment proposer mes outils ?',
    'contact.how_to_list_answer': 'Cliquez sur "Proposer un outil" dans la navigation, ajoutez les détails et photos de votre outil, et commencez à gagner de l\'argent.',
    'contact.insurance': 'Les outils sont-ils assurés ?',
    'contact.insurance_answer': 'Oui, tous les outils loués via Bricola sont couverts par notre assurance complète pour votre tranquillité d\'esprit.',

    // Add Tool
    'add_tool.title': 'Proposer un outil',
    'add_tool.subtitle': 'Partagez vos outils avec la communauté et générez des revenus en les louant facilement',
    'add_tool.info_title': 'Informations de l\'outil',
    'add_tool.general_info': 'Informations générales',
    'add_tool.ad_title': 'Titre de l\'annonce',
    'add_tool.brand': 'Marque',
    'add_tool.model': 'Modèle',
    'add_tool.year': 'Année d\'achat',
    'add_tool.description': 'Description',
    'add_tool.categorization': 'Catégorisation',
    'add_tool.category': 'Catégorie',
    'add_tool.subcategory': 'Sous-catégorie',
    'add_tool.condition': 'État de l\'outil',
    'add_tool.pricing': 'Tarification',
    'add_tool.price_per_day': 'Prix par jour (€)',
    'add_tool.deposit': 'Caution (€)',
    'add_tool.location_title': 'Localisation',
    'add_tool.address': 'Adresse ou ville',
    'add_tool.photos_title': 'Photos',
    'add_tool.add_photos': 'Ajoutez vos photos',
    'add_tool.drop_images': 'Glissez vos images ici ou cliquez pour parcourir',
    'add_tool.browse_files': 'Parcourir les fichiers',
    'add_tool.file_format': 'PNG, JPG jusqu\'à 10MB • 5 photos maximum',
    'add_tool.instructions_title': 'Consignes d\'utilisation',
    'add_tool.owner_instructions': 'Consignes du propriétaire',
    'add_tool.publish': 'Publier l\'annonce',
    'add_tool.choose_category': 'Choisir une catégorie',
    'add_tool.choose_subcategory': 'Choisir une sous-catégorie',
    'add_tool.condition_new': '✨ Neuf',
    'add_tool.condition_excellent': '🌟 Excellent',
    'add_tool.condition_good': '👍 Bon',
    'add_tool.condition_fair': '👌 Correct',

    // Categories
    'category.gardening': 'Jardinage',
    'category.diy': 'Bricolage',
    'category.transport': 'Transport',
    'category.cleaning': 'Nettoyage',
    'category.event': 'Événementiel',

    // Common
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.ok': 'OK',
    'common.language': 'Langue',
    'common.currency': 'Devise',
    'common.menu': 'Menu',
    'common.navigation': 'Navigation',
    'common.home': 'Accueil'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.catalog': 'Catalog',
    'nav.rent': 'Rent',
    'nav.list': 'List a tool',
    'nav.login': 'Login',
    'nav.signup': 'Sign up',
    
    // Hero section
    'hero.title': 'Rent and share your tools with ease',
    'hero.subtitle': 'The platform that connects tool owners with those who need them. Individuals and professionals, find the perfect tool near you.',
    'hero.search.placeholder': 'Search for a tool...',
    'hero.search.location': 'Location',
    'hero.search.button': 'Search',
    
    // Categories
    'categories.title': 'Popular categories',
    'categories.garden': 'Gardening',
    'categories.construction': 'Construction',
    'categories.automotive': 'Automotive',
    'categories.electric': 'Electric',
    
    // Tools
    'tools.featured': 'Featured tools',
    'tools.day': 'day',
    'tools.available': 'Available',
    'tools.rent': 'Rent',
    'tools.details': 'View details',
    'tools.new_ad': 'New ad',
    'tools.my_ads': 'My ads',
    'tools.edit': 'Edit',
    'tools.view': 'View',
    'tools.delete': 'Delete',
    'tools.published': 'Published',
    'tools.unpublished': 'Unpublished',
    'tools.pending': 'Pending',
    'tools.approved': 'Approved',
    'tools.rejected': 'Rejected',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.profile': 'Profile',
    'profile.wallet': 'Wallet',
    'profile.requests': 'Requests',
    'profile.reservations': 'Reservations',
    'profile.ads': 'Ads',
    'profile.favorites': 'Favorites',
    'profile.edit': 'Edit',
    'profile.save': 'Save',
    'profile.cancel': 'Cancel',
    'profile.verified': 'Verified',
    'profile.member_since': 'Member since',
    'profile.individual': 'Individual',
    'profile.company': 'Company',
    'profile.delete_account': 'Delete my account',
    'profile.delete_confirm': 'Delete your account',
    'profile.delete_description': 'Account deletion is irreversible.',
    'profile.back_home': 'Back to home',
    
    // Forms
    'form.first_name': 'First name',
    'form.last_name': 'Last name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.address': 'Address',
    'form.country': 'Country',
    'form.password': 'Password',
    'form.confirm_password': 'Confirm password',
    'form.title': 'Title',
    'form.description': 'Description',
    'form.price': 'Price',
    'form.category': 'Category',
    'form.location': 'Location',
    
    // Actions
    'action.search': 'Search',
    'action.filter': 'Filter',
    'action.sort': 'Sort',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.confirm': 'Confirm',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'action.view': 'View',
    'action.contact': 'Contact',
    'action.close': 'Close',
    'action.back': 'Back',
    'action.next': 'Next',
    'action.previous': 'Previous',
    
    // Floating Action Button
    'fab.contact_support': 'Contact support',
    'fab.publish_ad': 'Publish ad',
    'fab.find_tool': 'Find my tool',
    
    // Messages
    'message.success': 'Success',
    'message.error': 'Error',
    'message.loading': 'Loading...',
    'message.no_results': 'No results found',
    'message.confirm_delete': 'Are you sure you want to delete?',
    
    // Footer
    'footer.about': 'About',
    'footer.help': 'Help',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.rights': 'All rights reserved',
    'footer.cgu': 'Terms',
    'footer.privacy': 'Privacy policy',
    'footer.faq': 'FAQ',
    
    // Login
    'login.title': 'Login',
    'login.subtitle': 'Connect to your ToolShare account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.signin': 'Sign in',
    'login.no_account': 'No account yet? Sign up',
    'login.forgot_password': 'Forgot password?',

    // Register
    'register.title': 'Sign up',
    'register.subtitle': 'Create your ToolShare account',
    'register.user_type': 'User type',
    'register.individual': 'Individual',
    'register.business': 'Business',
    'register.first_name': 'First name',
    'register.last_name': 'Last name',
    'register.phone': 'Phone',
    'register.country': 'Country',
    'register.address': 'Address',
    'register.address_help': 'Complete address with postal code and city',
    'register.password': 'Password',
    'register.confirm_password': 'Confirm password',
    'register.terms': 'I accept the terms of use',
    'register.sales_conditions': 'I accept the terms and conditions and sales conditions',
    'register.create_account': 'Create my account',
    'register.have_account': 'Already have an account? Sign in',
    'register.select_country': 'Select a country',

    // About
    'about.title': 'About Bricola',
    'about.subtitle': 'The tool rental platform that revolutionizes DIY by connecting tool owners with those who need them.',
    'about.mission_title': 'Our Mission',
    'about.mission_1': 'At Bricola, we believe that every DIY project deserves access to the best tools, without having to buy them.',
    'about.mission_2': 'Our platform allows individuals and professionals to share their unused tools with their local community, creating a sustainable and economic ecosystem.',
    'about.mission_3': 'We facilitate access to quality tools while promoting the circular economy and local social connections.',
    'about.values_title': 'Our Values',
    'about.community': 'Community',
    'about.community_desc': 'Create connections between neighbors and promote local mutual aid',
    'about.security': 'Security',
    'about.security_desc': 'Guarantee secure transactions and comprehensive insurance',
    'about.quality': 'Quality',
    'about.quality_desc': 'Ensure all tools meet our quality standards',
    'about.simplicity': 'Simplicity',
    'about.simplicity_desc': 'Make tool rental as simple as a click',
    'about.stats_title': 'Bricola in numbers',
    'about.tools_available': 'Tools available',
    'about.active_users': 'Active users',
    'about.cities_covered': 'Cities covered',
    'about.satisfaction': 'Customer satisfaction',
    'about.team_title': 'Our Team',

    // Contact
    'contact.title': 'Contact us',
    'contact.subtitle': 'A question, a problem or just want to chat? Our team is here to help you.',
    'contact.form_title': 'Send us a message',
    'contact.first_name': 'First name',
    'contact.last_name': 'Last name',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send message',
    'contact.email_title': 'Email',
    'contact.phone_title': 'Phone',
    'contact.address_title': 'Address',
    'contact.hours_title': 'Hours',
    'contact.hours_weekdays': 'Monday - Friday: 9:00 AM - 6:00 PM',
    'contact.hours_saturday': 'Saturday: 10:00 AM - 4:00 PM',
    'contact.hours_sunday': 'Sunday: Closed',
    'contact.faq_title': 'Frequently asked questions',
    'contact.how_to_rent': 'How to rent a tool?',
    'contact.how_to_rent_answer': 'Search for the desired tool, select rental dates, and confirm your reservation. It\'s that simple!',
    'contact.problem': 'What to do in case of a problem?',
    'contact.problem_answer': 'Contact us immediately via our customer support. We are here to solve all your problems quickly.',
    'contact.how_to_list': 'How to list my tools?',
    'contact.how_to_list_answer': 'Click on "List a tool" in the navigation, add details and photos of your tool, and start earning money.',
    'contact.insurance': 'Are tools insured?',
    'contact.insurance_answer': 'Yes, all tools rented via Bricola are covered by our comprehensive insurance for your peace of mind.',

    // Add Tool
    'add_tool.title': 'List a tool',
    'add_tool.subtitle': 'Share your tools with the community and generate income by renting them easily',
    'add_tool.info_title': 'Tool information',
    'add_tool.general_info': 'General information',
    'add_tool.ad_title': 'Ad title',
    'add_tool.brand': 'Brand',
    'add_tool.model': 'Model',
    'add_tool.year': 'Purchase year',
    'add_tool.description': 'Description',
    'add_tool.categorization': 'Categorization',
    'add_tool.category': 'Category',
    'add_tool.subcategory': 'Subcategory',
    'add_tool.condition': 'Tool condition',
    'add_tool.pricing': 'Pricing',
    'add_tool.price_per_day': 'Price per day (€)',
    'add_tool.deposit': 'Deposit (€)',
    'add_tool.location_title': 'Location',
    'add_tool.address': 'Address or city',
    'add_tool.photos_title': 'Photos',
    'add_tool.add_photos': 'Add your photos',
    'add_tool.drop_images': 'Drop your images here or click to browse',
    'add_tool.browse_files': 'Browse files',
    'add_tool.file_format': 'PNG, JPG up to 10MB • 5 photos maximum',
    'add_tool.instructions_title': 'Usage instructions',
    'add_tool.owner_instructions': 'Owner instructions',
    'add_tool.publish': 'Publish ad',
    'add_tool.choose_category': 'Choose a category',
    'add_tool.choose_subcategory': 'Choose a subcategory',
    'add_tool.condition_new': '✨ New',
    'add_tool.condition_excellent': '🌟 Excellent',
    'add_tool.condition_good': '👍 Good',
    'add_tool.condition_fair': '👌 Fair',

    // Categories
    'category.gardening': 'Gardening',
    'category.diy': 'DIY',
    'category.transport': 'Transport',
    'category.cleaning': 'Cleaning',
    'category.event': 'Event',

    // Common
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.language': 'Language',
    'common.currency': 'Currency',
    'common.menu': 'Menu',
    'common.navigation': 'Navigation',
    'common.home': 'Home'
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.catalog': 'الكتالوج',
    'nav.rent': 'استئجار',
    'nav.list': 'إضافة أداة',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    
    // Hero section
    'hero.title': 'استأجر وشارك أدواتك بسهولة',
    'hero.subtitle': 'المنصة التي تربط أصحاب الأدوات مع من يحتاجونها. أفراد ومحترفون، اعثر على الأداة المثالية بالقرب منك.',
    'hero.search.placeholder': 'البحث عن أداة...',
    'hero.search.location': 'الموقع',
    'hero.search.button': 'بحث',
    
    // Categories
    'categories.title': 'الفئات الشائعة',
    'categories.garden': 'البستنة',
    'categories.construction': 'البناء',
    'categories.automotive': 'السيارات',
    'categories.electric': 'الكهرباء',
    
    // Tools
    'tools.featured': 'الأدوات المميزة',
    'tools.day': 'يوم',
    'tools.available': 'متاح',
    'tools.rent': 'استئجار',
    'tools.details': 'عرض التفاصيل',
    'tools.new_ad': 'إعلان جديد',
    'tools.my_ads': 'إعلاناتي',
    'tools.edit': 'تعديل',
    'tools.view': 'عرض',
    'tools.delete': 'حذف',
    'tools.published': 'منشور',
    'tools.unpublished': 'غير منشور',
    'tools.pending': 'في الانتظار',
    'tools.approved': 'مُوافق عليه',
    'tools.rejected': 'مرفوض',
    
    // Profile
    'profile.title': 'ملفي الشخصي',
    'profile.profile': 'الملف الشخصي',
    'profile.wallet': 'المحفظة',
    'profile.requests': 'الطلبات',
    'profile.reservations': 'الحجوزات',
    'profile.ads': 'الإعلانات',
    'profile.favorites': 'المفضلة',
    'profile.edit': 'تعديل',
    'profile.save': 'حفظ',
    'profile.cancel': 'إلغاء',
    'profile.verified': 'موثق',
    'profile.member_since': 'عضو منذ',
    'profile.individual': 'فرد',
    'profile.company': 'شركة',
    'profile.delete_account': 'حذف حسابي',
    'profile.delete_confirm': 'حذف حسابك',
    'profile.delete_description': 'حذف الحساب غير قابل للإلغاء.',
    'profile.back_home': 'العودة للرئيسية',
    
    // Forms
    'form.first_name': 'الاسم الأول',
    'form.last_name': 'الاسم الأخير',
    'form.email': 'البريد الإلكتروني',
    'form.phone': 'الهاتف',
    'form.address': 'العنوان',
    'form.country': 'البلد',
    'form.password': 'كلمة المرور',
    'form.confirm_password': 'تأكيد كلمة المرور',
    'form.title': 'العنوان',
    'form.description': 'الوصف',
    'form.price': 'السعر',
    'form.category': 'الفئة',
    'form.location': 'الموقع',
    
    // Actions
    'action.search': 'بحث',
    'action.filter': 'تصفية',
    'action.sort': 'ترتيب',
    'action.save': 'حفظ',
    'action.cancel': 'إلغاء',
    'action.confirm': 'تأكيد',
    'action.delete': 'حذف',
    'action.edit': 'تعديل',
    'action.view': 'عرض',
    'action.contact': 'اتصال',
    'action.close': 'إغلاق',
    'action.back': 'رجوع',
    'action.next': 'التالي',
    'action.previous': 'السابق',
    
    // Floating Action Button
    'fab.contact_support': 'اتصل بالدعم',
    'fab.publish_ad': 'نشر إعلان',
    'fab.find_tool': 'البحث عن أداة',
    
    // Messages
    'message.success': 'نجح',
    'message.error': 'خطأ',
    'message.loading': 'جاري التحميل...',
    'message.no_results': 'لم يتم العثور على نتائج',
    'message.confirm_delete': 'هل أنت متأكد من الحذف؟',
    
    // Footer
    'footer.about': 'حول',
    'footer.help': 'مساعدة',
    'footer.contact': 'اتصال',
    'footer.legal': 'قانوني',
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.cgu': 'الشروط',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.faq': 'الأسئلة الشائعة',
    
    // Login
    'login.title': 'تسجيل الدخول',
    'login.subtitle': 'اتصل بحسابك في ToolShare',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.signin': 'تسجيل الدخول',
    'login.no_account': 'ليس لديك حساب؟ إنشاء حساب',
    'login.forgot_password': 'نسيت كلمة المرور؟',

    // Register
    'register.title': 'إنشاء حساب',
    'register.subtitle': 'أنشئ حسابك في ToolShare',
    'register.user_type': 'نوع المستخدم',
    'register.individual': 'فرد',
    'register.business': 'شركة',
    'register.first_name': 'الاسم الأول',
    'register.last_name': 'الاسم الأخير',
    'register.phone': 'الهاتف',
    'register.country': 'البلد',
    'register.address': 'العنوان',
    'register.address_help': 'العنوان الكامل مع الرمز البريدي والمدينة',
    'register.password': 'كلمة المرور',
    'register.confirm_password': 'تأكيد كلمة المرور',
    'register.terms': 'أوافق على شروط الاستخدام',
    'register.sales_conditions': 'أوافق على الشروط والأحكام وشروط البيع',
    'register.create_account': 'إنشاء حسابي',
    'register.have_account': 'لديك حساب بالفعل؟ تسجيل الدخول',
    'register.select_country': 'اختر بلداً',

    // About
    'about.title': 'حول Bricola',
    'about.subtitle': 'منصة تأجير الأدوات التي تثور في مجال الأعمال اليدوية من خلال ربط أصحاب الأدوات مع من يحتاجونها.',
    'about.mission_title': 'مهمتنا',
    'about.mission_1': 'في Bricola، نؤمن أن كل مشروع يدوي يستحق الوصول إلى أفضل الأدوات، دون الحاجة لشرائها.',
    'about.mission_2': 'تسمح منصتنا للأفراد والمحترفين بمشاركة أدواتهم غير المستخدمة مع مجتمعهم المحلي، مما يخلق نظاماً بيئياً مستداماً واقتصادياً.',
    'about.mission_3': 'نسهل الوصول إلى الأدوات عالية الجودة مع تعزيز الاقتصاد الدائري والروابط الاجتماعية المحلية.',
    'about.values_title': 'قيمنا',
    'about.community': 'المجتمع',
    'about.community_desc': 'إنشاء روابط بين الجيران وتعزيز التعاون المحلي',
    'about.security': 'الأمان',
    'about.security_desc': 'ضمان المعاملات الآمنة والتأمين الشامل',
    'about.quality': 'الجودة',
    'about.quality_desc': 'التأكد من أن جميع الأدوات تلبي معايير الجودة لدينا',
    'about.simplicity': 'البساطة',
    'about.simplicity_desc': 'جعل تأجير الأدوات بسيط كالنقر على زر',
    'about.stats_title': 'Bricola في الأرقام',
    'about.tools_available': 'الأدوات المتاحة',
    'about.active_users': 'المستخدمون النشطون',
    'about.cities_covered': 'المدن المغطاة',
    'about.satisfaction': 'رضا العملاء',
    'about.team_title': 'فريقنا',

    // Contact
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'لديك سؤال أو مشكلة أو تريد التحدث؟ فريقنا هنا لمساعدتك.',
    'contact.form_title': 'أرسل لنا رسالة',
    'contact.first_name': 'الاسم الأول',
    'contact.last_name': 'الاسم الأخير',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال الرسالة',
    'contact.email_title': 'البريد الإلكتروني',
    'contact.phone_title': 'الهاتف',
    'contact.address_title': 'العنوان',
    'contact.hours_title': 'ساعات العمل',
    'contact.hours_weekdays': 'الاثنين - الجمعة: 9:00 صباحاً - 6:00 مساءً',
    'contact.hours_saturday': 'السبت: 10:00 صباحاً - 4:00 مساءً',
    'contact.hours_sunday': 'الأحد: مغلق',
    'contact.faq_title': 'الأسئلة الشائعة',
    'contact.how_to_rent': 'كيفية استئجار أداة؟',
    'contact.how_to_rent_answer': 'ابحث عن الأداة المطلوبة، اختر تواريخ الاستئجار، وأكد حجزك. الأمر بهذه البساطة!',
    'contact.problem': 'ماذا أفعل في حالة وجود مشكلة؟',
    'contact.problem_answer': 'اتصل بنا فوراً عبر دعم العملاء. نحن هنا لحل جميع مشاكلك بسرعة.',
    'contact.how_to_list': 'كيفية عرض أدواتي؟',
    'contact.how_to_list_answer': 'انقر على "عرض أداة" في التنقل، أضف تفاصيل وصور أداتك، وابدأ في كسب المال.',
    'contact.insurance': 'هل الأدوات مؤمنة؟',
    'contact.insurance_answer': 'نعم، جميع الأدوات المستأجرة عبر Bricola مغطاة بتأميننا الشامل لراحة بالك.',

    // Add Tool
    'add_tool.title': 'عرض أداة',
    'add_tool.subtitle': 'شارك أدواتك مع المجتمع واحصل على دخل من تأجيرها بسهولة',
    'add_tool.info_title': 'معلومات الأداة',
    'add_tool.general_info': 'المعلومات العامة',
    'add_tool.ad_title': 'عنوان الإعلان',
    'add_tool.brand': 'العلامة التجارية',
    'add_tool.model': 'الطراز',
    'add_tool.year': 'سنة الشراء',
    'add_tool.description': 'الوصف',
    'add_tool.categorization': 'التصنيف',
    'add_tool.category': 'الفئة',
    'add_tool.subcategory': 'الفئة الفرعية',
    'add_tool.condition': 'حالة الأداة',
    'add_tool.pricing': 'التسعير',
    'add_tool.price_per_day': 'السعر في اليوم (€)',
    'add_tool.deposit': 'التأمين (€)',
    'add_tool.location_title': 'الموقع',
    'add_tool.address': 'العنوان أو المدينة',
    'add_tool.photos_title': 'الصور',
    'add_tool.add_photos': 'أضف صورك',
    'add_tool.drop_images': 'اسحب صورك هنا أو انقر للتصفح',
    'add_tool.browse_files': 'تصفح الملفات',
    'add_tool.file_format': 'PNG، JPG حتى 10MB • 5 صور كحد أقصى',
    'add_tool.instructions_title': 'تعليمات الاستخدام',
    'add_tool.owner_instructions': 'تعليمات المالك',
    'add_tool.publish': 'نشر الإعلان',
    'add_tool.choose_category': 'اختر فئة',
    'add_tool.choose_subcategory': 'اختر فئة فرعية',
    'add_tool.condition_new': '✨ جديد',
    'add_tool.condition_excellent': '🌟 ممتاز',
    'add_tool.condition_good': '👍 جيد',
    'add_tool.condition_fair': '👌 مقبول',

    // Categories
    'category.gardening': 'البستنة',
    'category.diy': 'الأعمال اليدوية',
    'category.transport': 'النقل',
    'category.cleaning': 'التنظيف',
    'category.event': 'المناسبات',

    // Common
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.ok': 'موافق',
    'common.language': 'اللغة',
    'common.currency': 'العملة',
    'common.menu': 'القائمة',
    'common.navigation': 'التنقل',
    'common.home': 'الرئيسية'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  // Set document direction for Arabic
  React.useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
