import React, { createContext, useContext, useState } from 'react';

type Language = 'fr' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // pagination
    'pagination.next': 'Suivant',
    'pagination.previous': 'Précédent',

    // catalog section
    'catalog_section.title': 'Outils trouvés',
    'catalog_section.by': 'Par',
    'catalog_section.category': 'Catégorie',
    'catalog_section.sort_by': 'Trier par',
    'catalog_section.most_recent': 'Plus récents',
    'catalog_section.price_low_to_high': 'Prix croissant',
    'catalog_section.price_high_to_low': 'Prix décroissant',
    'catalog_section.top_rated': 'Mieux notés',
    'catalog_section.filters': 'Filtres',
    'catalog_section.search': 'Recherche',
    'catalog_section.tool_name': 'Nom de l\'outil',
    'catalog_section.location': 'Localisation',
    'catalog_section.all_categories': 'Toutes les catégories',
    'catalog_section.sub_category': 'Sous-catégorie',
    'catalog_section.all_sub_categories': 'Toutes les sous-catégories',
    'catalog_section.daily_price': 'Prix par jour',
    'catalog_section.apply_filters': 'Appliquer les filtres',


    // blog section
    'blog_section.title': 'Derniers articles du blog',
    'blog_section.description': 'Découvrez nos conseils, guides et actualités pour réussir tous vos projets de bricolage',
    'blog_section.min': 'min',
    'blog_section.read_article': 'Lire l\'article',
    'blog_section.view_all': 'Voir tous les articles',

    // customer reviews
    'customer_reviews.title': 'Avis de nos clients',
    'customer_reviews.description': 'Découvrez ce que nos utilisateurs pensent de notre plateforme',

    // rental process
    'rental_process.title': 'Comment ça marche ?',
    'rental_process.description': 'Louez vos outils en 4 étapes simples et commencez à générer des revenus',
    'rental_process.step1.title': 'Publiez votre annonce en quelques clics',
    'rental_process.step1.description': 'Ajoutez vos outils avec photos et description détaillée en quelques minutes seulement.',
    'rental_process.step2.title': 'Maximisez votre visibilité',
    'rental_process.step2.description': 'Votre annonce est visible par des milliers d\'utilisateurs à la recherche d\'outils.',
    'rental_process.step3.title': 'Recevez vos premières réservations',
    'rental_process.step3.description': 'Les locataires vous contactent directement pour réserver vos outils aux dates souhaitées.',
    'rental_process.step4.title': 'Percevez vos revenus en toute sérénité',
    'rental_process.step4.description': 'Recevez vos paiements de manière sécurisée et générez des revenus supplémentaires.',

    // Profile translations (some already added from ProfileInfo)
    'profile.first_name': 'Prénom',
    'profile.last_name': 'Nom',
    'profile.email': 'Email',
    'profile.phone': 'Téléphone',
    'profile.country': 'Pays',
    'profile.address': 'Adresse',
    'profile.edit_profile_photo': 'Cliquez sur "Modifier" pour changer votre photo de profil',
    'profile.verified': 'Vérifié',
    'profile.account_type_individual': 'Particulier',
    'profile.account_type_company': 'Entreprise',
    'profile.average_rating': 'Note moyenne',
    'profile.rentals_completed': 'Locations réalisées',
    'profile.active_ads': 'Annonces actives',
    'profile.total_earnings': 'Gains totaux',
    'profile.delete_account': 'Supprimer mon compte',
    'profile.back_home': 'Retour à l\'accueil',
    'profile.profile': 'Profil',
    'profile.favorites': 'Favoris',
    'profile.ads': 'Annonces',
    'profile.reservations': 'Réservations',
    'profile.requests': 'Demandes',
    'profile.wallet': 'Portefeuille',
    'profile.edit': 'Modifier',
    'profile.member_since': 'Membre depuis {date}',
    'profile.select_country': 'Sélectionnez un pays',
    'profile.address_placeholder': 'Saisissez votre adresse complète',
    'profile.address_hint': 'Saisissez une adresse valide compatible avec Google Maps',
    'profile.delete_confirm': 'Confirmez-vous la suppression de votre compte ?',
    'profile.delete_description': 'Cette action est irréversible. Toutes vos données, annonces, réservations et historique de transactions seront définitivement supprimés.',
    'profile.account_deletion_pending': 'Compte en attente de suppression',

    // Action translations (assuming these exist from previous context)
    'action.cancel': 'Annuler',
    'action.confirm': 'Confirmer',
    
 // Wallet translations
    'wallet.title': 'Mon Portefeuille',
    'wallet.total': 'Total',
    'wallet.cumulative_balance': 'Solde cumulé',
    'wallet.available': 'Disponible',
    'wallet.available_balance': 'Solde disponible',
    'wallet.successful': 'Réussies',
    'wallet.successful_transactions': 'Transactions réussies',
    'wallet.withdraw_money': 'Retirer mon argent',
    'wallet.withdrawal_note': 'Vous pouvez retirer votre argent à partir du moment où votre solde cumulé atteint 20 GBP.',
    'wallet.conversion_rate': '20 GBP = {minWithdrawalEUR} EUR',
    'wallet.dynamic_conversion': 'Le taux de conversion s\'actualise dynamiquement en fonction de la devise choisie dans le compte.',

    // recent transactions
    'wallet.recent_transactions': 'Transactions récentes',
    'wallet.select_time_period': 'Sélectionnez une période',
    'wallet.all_transactions': 'Toutes les transactions',
    'wallet.incoming_payments': 'Receptions',
    'wallet.withdrawal': 'Retrait',
    'wallet.reset': 'Réinitialiser',
    'wallet.completed': 'Terminée',
    'wallet.pending': 'En attente',
    'wallet.failed': 'Échouée',
    
    // New FAQ translations
    'faq.hero.title': 'Questions Fréquentes',
    'faq.hero.subtitle': 'Trouvez rapidement les réponses à vos questions les plus courantes',
    'faq.title': 'Questions générales',
    'faq.general.q1': 'Qu’est-ce que Bricola et comment ça fonctionne ?',
    'faq.general.a1': 'Bricola LTD est une plateforme de location d’outils entre particuliers. Les utilisateurs peuvent proposer leurs outils à la location ou en louer auprès d\'autres membres. La plateforme gère les paiements, les cautions et les litiges.',
    'faq.general.q2': 'Quelles catégories d’outils peut-on proposer ?',
    'faq.general.a2': 'Actuellement, Bricola prend en charge les outils de bricolage, jardinage, nettoyage et ceux liés aux événements. D’autres catégories pourront être ajoutées selon les besoins du marché.',
    'faq.general.q3': 'Existe-t-il une application mobile Bricola ?',
    'faq.general.a3': 'Oui. Bricola est disponible sur iOS et Android, en plus de la version complète du site web.',
    'faq.general.q4': 'Puis-je utiliser Bricola depuis n’importe quel pays ?',
    'faq.general.a4': 'Pour le moment, Bricola est disponible uniquement dans la région du Golfe. Une expansion est prévue prochainement.',
    'faq.general.q5': 'Les entreprises peuvent-elles proposer des outils ?',
    'faq.general.a5': 'Oui, mais Bricola est principalement destiné aux particuliers. Les professionnels doivent respecter les lois et réglementations locales en vigueur.',
    'faq.general.q6': 'Quels objets sont interdits ?',
    'faq.general.a6': 'Sont interdits : les objets illégaux, les équipements dangereux ou non conformes aux normes de sécurité.',
    'faq.general.q7': 'Puis-je suggérer une fonctionnalité ?',
    'faq.general.a7': 'Oui, vos suggestions sont les bienvenues. Contactez notre support pour nous faire part de votre idée, nous l’étudierons pour les prochaines mises à jour.',
    'faq.general.q8': 'Comment contacter le service client ?',
    'faq.general.a8': 'Utilisez le chat WhatsApp ou envoyez-nous un email à : support@bricolaltd.com. Notre équipe est disponible 7 jours sur 7.',
    'faq.renters.title': 'Pour les locataires',
    'faq.renters.q1': 'Comment créer un compte ?',
    'faq.renters.a1': 'Il suffit de s’inscrire avec votre nom, votre email, votre numéro de téléphone et, si nécessaire, vos documents de vérification. Vous devrez confirmer votre numéro et votre adresse email.',
    'faq.renters.q2': 'Pourquoi la vérification d’identité est-elle demandée ?',
    'faq.renters.a2': 'Pour garantir la sécurité et la confiance sur la plateforme, une vérification d’identité peut être exigée avant de louer des outils de grande valeur ou d’effectuer des retraits importants.',
    'faq.renters.q3': 'Que dois-je faire avant de recevoir un outil ?',
    'faq.renters.a3': 'Assurez-vous de fournir une pièce d’identité valide, respectez les conditions de location, et examinez l’outil avec le propriétaire à la remise.',
    'faq.renters.q4': 'Que faire si l’outil est endommagé pendant la location ?',
    'faq.renters.a4': 'Informez immédiatement le propriétaire et le support. Des preuves peuvent être demandées pour activer un recours via la caution.',
    'faq.owners.title': 'Pour les propriétaires',
    'faq.owners.q1': 'Comment proposer un outil à la location ?',
    'faq.owners.a1': 'Cliquez sur « Proposer un outil », téléchargez des photos claires, ajoutez une description, précisez l’état de l’outil, les garanties éventuelles, le prix par jour et le montant de la caution.',
    'faq.owners.q2': 'Que se passe-t-il après avoir proposé mon outil ?',
    'faq.owners.a2': 'L’annonce sera d’abord vérifiée par notre équipe de modération. Vous serez ensuite notifié dès qu’un utilisateur effectue une réservation.',
    'faq.owners.q3': 'Puis-je refuser une demande de réservation ?',
    'faq.owners.a3': 'Oui, le propriétaire peut accepter ou refuser une demande. Cependant, un trop grand nombre de refus sans justification peut nuire à la visibilité de vos annonces.',
    'faq.owners.q4': 'Que dois-je faire avant de remettre l’outil au locataire ?',
    'faq.owners.a4': 'Vérifiez l’identité du locataire, prenez des photos de l’état de l’outil, et convenez ensemble des conditions de retour.',
    'faq.owners.q5': 'Que faire si mon outil est endommagé ?',
    'faq.owners.a5': 'Envoyez des preuves dans les 24 heures suivant le retour. L’équipe Bricola examinera le dossier et pourra décider d’un remboursement à partir de la caution.',
    'faq.owners.q6': 'Y a-t-il une assurance sur les outils proposés ?',
    'faq.owners.a6': 'Non, Bricola ne propose pas encore d’assurance. Il est recommandé de ne proposer que les outils que vous êtes prêt à prêter en toute sécurité.',
    'faq.payment.title': 'Paiement et sécurité',
    'faq.payment.q1': 'Comment se passent les paiements ?',
    'faq.payment.a1': 'Les paiements sont traités de manière sécurisée via Stripe. Le locataire paie à l’avance, y compris la caution.',
    'faq.payment.q2': 'Qu’est-ce que la caution ?',
    'faq.payment.a2': 'Il s’agit d’un montant remboursable, conservé par Stripe pour couvrir d’éventuels dommages ou non-retours. Il est automatiquement restitué après le bon retour de l’outil.',
    'faq.payment.q3': 'Comment retirer mes gains ?',
    'faq.payment.a3': 'Vous pouvez demander un virement vers votre compte bancaire via Wise.',
    'faq.payment.q4': 'Quels sont les frais appliqués par Bricola ?',
    'faq.payment.a4': 'Bricola prélève une commission de 15 % sur chaque location réussie. Aucun frais d’inscription ou abonnement mensuel.',
    'faq.payment.q5': 'Comment sont traités les litiges ?',
    'faq.payment.a5': 'Tous les litiges sont gérés par notre équipe d’assistance dans un délai de 72 heures. Leur décision est finale.',
    'faq.payment.q6': 'Quelles mesures de sécurité sont mises en place ?',
    'faq.payment.a6': 'Vérification d’identité, évaluations utilisateurs, paiements sécurisés et surveillance par notre support assurent un environnement fiable.',
    
    // Navigation
    'nav.home': 'Accueil',
    'nav.catalog': 'Catalogue',
    'nav.navigation': 'navigation',
    'nav.propos': 'À propos',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact',
    'nav.rent': 'Louer',
    'nav.list': 'Proposer un outil',
    'nav.login': 'Connexion',
    'nav.signup': 'Inscription',
    
    // Hero section
    'hero.title': 'Louez et partagez vos outils en toute simplicité',
    'hero.subtitle': 'La plateforme qui connecte les propriétaires d\'outils avec ceux qui en ont besoin. Particuliers et professionnels, trouvez l\'outil parfait près de chez vous.',
    'hero.search.placeholder': 'Rechercher un outil...',
    'hero.search.location': 'Localisation',
    'hero.search.button': 'Rechercher',
    'hero.available_tools': 'Outils disponibles',
    'hero.active_users': 'Utilisateurs actifs',
    'hero.cities_covered': 'Villes couvertes',
    
    // Categories
    'categories.title': 'Nos catégories',
    'categories.description': 'Trouvez l\'outil parfait selon vos besoins',
    'categories.gardening': 'Jardinage',
    'categories.cleaning': 'Nettoyage',
    'categories.diy': 'Bricolage',
    'categories.events': 'Événementiel',
    'categories.transport': 'Transport',
    
    // Tools
    'tools.featured': 'Outils en vedette',
    'tools.description': 'Les outils les mieux notés et les plus demandés de notre communauté',
    'tools.day': 'jour',
    'tools.display_all': 'Voir tous les outils',
    'tools.by': 'par',
    'tools.available': 'Disponible',
    'tools.rent': 'Louer',
    'tools.details': 'Voir détails',
    'tools.new_ad': 'Nouvelle annonce',
    'tools.my_ads': 'Mes annonces',
    'tools.edit': 'Modifier',
    'tools.view': 'Voir',
    'tools.delete': 'Supprimer',
    'tools.published': 'Publié',
    'tools.unpublished': 'Non publié',
    'tools.pending': 'En attente',
    'tools.approved': 'Approuvé',
    'tools.rejected': 'Rejeté',
    'tools.back_to_results': 'Retour aux résultats',
    'tools.verified': 'Vérifié',
    'tools.owner': 'Propriétaire',
    'tools.model': 'Modèle',
    'tools.brand': 'Marque',
    'tools.year_of_purchase': 'Année d\'achat',
    'tools.fees_and_taxes': 'Incluant taxes et frais',
    'tools.of': 'des',
    'tools.charged': 'saisis par le loueur',
    'tools.deposit': 'Caution',
    'tools.refunded': '(remboursée en fin de location)',
    'tools.rent_now': 'Louer maintenant',
    'tools.add_to_favorites': 'Ajouter aux favoris',
    'tools.desc': 'Description',
    'tools.remove_from_favorites': 'Retirer des favoris',
    'tools.instructions': 'Consigne du propriétaire',
    'tools.reviews': 'Avis des locataires',


    // Forms
    'form.first_name': 'Prénom',
    'form.last_name': 'Nom',
    'form.email': 'Email',
    'form.phone': 'Téléphone',
    'form.address': 'Adresse',
    'form.country': 'Pays',
    'form.password': 'Mot de passe',
    'form.confirm_password': 'Confirmer le mot de passe',
    'form.title': 'Titre',
    'form.description': 'Description',
    'form.price': 'Prix',
    'form.category': 'Catégorie',
    'form.location': 'Localisation',
    
    // Actions
    'action.search': 'Rechercher',
    'action.filter': 'Filtrer',
    'action.sort': 'Trier',
    'action.save': 'Enregistrer',
    'action.delete': 'Supprimer',
    'action.edit': 'Modifier',
    'action.view': 'Voir',
    'action.contact': 'Contacter',
    'action.close': 'Fermer',
    'action.back': 'Retour',
    'action.next': 'Suivant',
    'action.previous': 'Précédent',
    
    // Floating Action Button
    'fab.contact_support': 'Contacter le support',
    'fab.publish_ad': 'Publier une annonce',
    'fab.find_tool': 'Trouver mon outil',
    
    // Messages
    'message.success': 'Succès',
    'message.error': 'Erreur',
    'message.loading': 'Chargement...',
    'message.no_results': 'Aucun résultat trouvé',
    'message.confirm_delete': 'Êtes-vous sûr de vouloir supprimer ?',
    
    // Footer
    'footer.about': 'À propos',
    'footer.help': 'Aide',
    'footer.contact': 'Contact',
    'footer.legal': 'Mentions légales',
    'footer.rights': 'Tous droits réservés',
    'footer.cgu': 'CGU',
    'footer.privacy': 'Politique de confidentialité',
    'footer.faq': 'FAQ',
    'footer.description': 'La plateforme de location d`\'outils qui connecte les propriétaires avec ceux qui en ont besoin. Simple, sécurisé et local.',
    'footer.contrat': 'Contrat de location', // Added
    'footer.payment': 'Modes de paiement', // Added
    'footer.useful_links': 'Liens utiles', // Added
    'footer.help_center': 'Centre d\'assistance', // Added
    'footer.owner_guide': 'Guide du loueur', // Added
    'footer.renter_guide': 'Guide du locataire', // Added
    'footer.terms_conditions': 'CGU', // Added (synonym for footer.cgu)
    // Login
    'login.title': 'Connexion',
    'login.subtitle': 'Connectez-vous à votre compte Bricola LTD',
    'login.email': 'Email',
    'login.password': 'Mot de passe',
    'login.signin': 'Se connecter',
    'login.no_account': 'Pas encore de compte ? S\'inscrire',
    'login.forgot_password': 'Mot de passe oublié ?',

    // Register
    'register.title': 'Inscription',
    'register.subtitle': 'Créez votre compte Bricola LTD',
    'register.user_type': 'Type d\'utilisateur',
    'register.individual': 'Particulier',
    'register.business': 'Entreprise',
    'register.first_name': 'Prénom',
    'register.last_name': 'Nom',
    'register.phone': 'Téléphone',
    'register.country': 'Pays',
    'register.address': 'Adresse',
    'register.address_help': 'Adresse complète avec code postal et ville',
    'register.password': 'Mot de passe',
    'register.confirm_password': 'Confirmer le mot de passe',
    'register.terms': 'J\'accepte les conditions d\'utilisation',
    'register.sales_conditions': 'J\'accepte les termes et conditions et les conditions de vente',
    'register.create_account': 'Créer mon compte',
    'register.have_account': 'Déjà un compte ? Se connecter',
    'register.select_country': 'Sélectionnez un pays',

    // About
    'about.title': 'Bienvenue chez Bricola LTD',
    'about.subtitle': 'Votre plateforme de confiance pour la location d’outils entre particuliers dans toute la région du Golfe.',
    'about.mission_title': 'Notre Mission',
    'about.mission_1': 'Fondée en 2025 et enregistrée au Royaume-Uni, Bricola LTD est née d’un constat simple mais essentiel : beaucoup de personnes possèdent des outils qu’elles utilisent rarement, tandis que d’autres en ont régulièrement besoin sans vouloir les acheter. Notre plateforme répond à ce besoin en permettant aux particuliers de louer des outils entre eux de manière sécurisée, économique et pratique.',
    'about.mission_2': 'Nous mettons en relation les personnes à la recherche d’outils pour des travaux domestiques, du jardinage, du nettoyage ou des événements, avec des propriétaires locaux d’outils. Grâce à notre application et notre site web intuitifs, il est possible de proposer, rechercher et louer des outils en quelques minutes.',
    'about.mission_3': 'Chez Bricola, nous croyons au potentiel de l’économie du partage pour réduire le gaspillage, encourager la durabilité et renforcer les liens communautaires. Notre service est conçu pour être sûr, transparent et centré sur la confiance des utilisateurs. Avec un système de paiement numérique fiable et des fonctionnalités de sécurité intégrées, Bricola garantit des transactions fluides et protégées.',
    'about.mission_4': 'En choisissant Bricola LTD, vous gagnez du temps et de l’argent, tout en adoptant une approche plus intelligente et écologique pour accéder aux outils dont vous avez besoin. Nous sommes fiers de construire l’avenir de la location d’outils dans la région du Golfe.',
    'about.mission_5': 'Merci de faire partie de la communauté Bricola.',
    'about.values_title': 'Nos Valeurs',
    'about.community': 'Communauté',
    'about.community_desc': 'Créer des liens entre voisins et favoriser l\'entraide locale',
    'about.security': 'Sécurité',
    'about.security_desc': 'Garantir des transactions sécurisées et une assurance complète',
    'about.quality': 'Qualité',
    'about.quality_desc': 'S\'assurer que tous les outils respectent nos standards de qualité',
    'about.simplicity': 'Simplicité',
    'about.simplicity_desc': 'Rendre la location d\'outils aussi simple qu\'un clic',
    'about.stats_title': 'Bricola en chiffres',
    'about.tools_available': 'Outils disponibles',
    'about.active_users': 'Utilisateurs actifs',
    'about.cities_covered': 'Villes couvertes',
    'about.satisfaction': 'Satisfaction client',
    'about.team_title': 'Notre Équipe',

    // Contact
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Une question, un problème ou simplement envie d\'échanger ? Notre équipe est là pour vous aider.',
    'contact.form_title': 'Envoyez-nous un message',
    'contact.first_name': 'Prénom',
    'contact.last_name': 'Nom',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le message',
    'contact.email_title': 'Email',
    'contact.phone_title': 'Téléphone',
    'contact.address_title': 'Adresse',
    'contact.hours_title': 'Horaires',
    'contact.hours_weekdays': 'Lundi - Vendredi : 9h00 - 18h00',
    'contact.hours_saturday': 'Samedi : 10h00 - 16h00',
    'contact.hours_sunday': 'Dimanche : Fermé',
    'contact.faq_title': 'Questions fréquentes',
    'contact.how_to_rent': 'Comment louer un outil ?',
    'contact.how_to_rent_answer': 'Recherchez l\'outil souhaité, sélectionnez les dates de location, et confirmez votre réservation. C\'est aussi simple que ça !',
    'contact.problem': 'Que faire en cas de problème ?',
    'contact.problem_answer': 'Contactez-nous immédiatement via notre support client. Nous sommes là pour résoudre tous vos problèmes rapidement.',
    'contact.how_to_list': 'Comment proposer mes outils ?',
    'contact.how_to_list_answer': 'Cliquez sur "Proposer un outil" dans la navigation, ajoutez les détails et photos de votre outil, et commencez à gagner de l\'argent.',
    'contact.insurance': 'Les outils sont-ils assurés ?',
    'contact.insurance_answer': 'Oui, tous les outils loués via Bricola sont couverts par notre assurance complète pour votre tranquillité d\'esprit.',

    // Add Tool
    'add_tool.title': 'Proposer un outil',
    'add_tool.subtitle': 'Partagez vos outils avec la communauté et générez des revenus en les louant facilement',
    'add_tool.info_title': 'Informations de l\'outil',
    'add_tool.general_info': 'Informations générales',
    'add_tool.ad_title': 'Titre de l\'annonce',
    'add_tool.brand': 'Marque',
    'add_tool.model': 'Modèle',
    'add_tool.year': 'Année d\'achat',
    'add_tool.description': 'Description',
    'add_tool.categorization': 'Catégorisation',
    'add_tool.category': 'Catégorie',
    'add_tool.subcategory': 'Sous-catégorie',
    'add_tool.condition': 'État de l\'outil',
    'add_tool.pricing': 'Tarification',
    'add_tool.price_per_day': 'Prix par jour (€)',
    'add_tool.deposit': 'Caution (€)',
    'add_tool.location_title': 'Localisation',
    'add_tool.address': 'Adresse ou ville',
    'add_tool.photos_title': 'Photos',
    'add_tool.add_photos': 'Ajoutez vos photos',
    'add_tool.drop_images': 'Glissez vos images ici ou cliquez pour parcourir',
    'add_tool.browse_files': 'Parcourir les fichiers',
    'add_tool.file_format': 'PNG, JPG jusqu\'à 10MB • 5 photos maximum',
    'add_tool.instructions_title': 'Consignes d\'utilisation',
    'add_tool.owner_instructions': 'Consignes du propriétaire',
    'add_tool.publish': 'Publier l\'annonce',
    'add_tool.choose_category': 'Choisir une catégorie',
    'add_tool.choose_subcategory': 'Choisir une sous-catégorie',
    'add_tool.condition_new': '✨ Neuf',
    'add_tool.condition_excellent': '🌟 Excellent',
    'add_tool.condition_good': '👍 Bon',
    'add_tool.condition_fair': '👌 Correct',

    // Categories and subcategories
    'category.gardening': 'Jardinage',
    'category.gardening.lawn': 'Gazon',
    'category.gardening.soil': 'Terre',
    'category.gardening.wood': 'Bois',
    'category.gardening.tree': 'Arbre',
    'category.gardening.leaves': 'Feuilles',

    'category.cleaning': 'Nettoyage',
    'category.cleaning.fabric': 'Tissu',
    'category.cleaning.water': 'Eau',
    'category.cleaning.dust': 'Poussière',

    'category.diy': 'Bricolage',
    'category.diy.construction': 'Construction',
    'category.diy.electricity': 'Électricité',
    'category.diy.painting': 'Peinture',
    'category.diy.screws_and_bolts': 'Vis et boulons',

    'category.transport': 'Transport',
    'category.transport.heavy_load': 'Charge lourde',
    'category.transport.engine': 'Moteur',
    'category.transport.wheel': 'Roue',

    'category.event': 'Événementiel',
    'category.event.lighting': 'Éclairage',
    'category.event.kitchen': 'Cuisine',
    'category.event.entertainment_and_games': 'Animation et jeux',
    'category.event.furniture': 'Mobilier',
    'category.event.decoration': 'Décoration',
    'category.event.structure': 'Structure',

    // Common
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.ok': 'OK',
    'common.language': 'Langue',
    'common.currency': 'Devise',
    'common.menu': 'Menu',
    'common.navigation': 'Navigation',
    'common.home': 'Accueil'
  },
  en: {

    // pagination
    'pagination.next': 'Next',
    'pagination.previous': 'Previous',

    // catalog section
    'catalog_section.title': 'Tools Found',
    'catalog_section.by': 'By',
    'catalog_section.category': 'Category',
    'catalog_section.sort_by': 'Sort by',
    'catalog_section.most_recent': 'Most Recent',
    'catalog_section.price_low_to_high': 'Price: Low to High',
    'catalog_section.price_high_to_low': 'Price: High to Low',
    'catalog_section.top_rated': 'Top Rated',
    'catalog_section.filters': 'Filters',
    'catalog_section.search': 'Search',
    'catalog_section.tool_name': 'Tool Name',
    'catalog_section.location': 'Location',
    'catalog_section.all_categories': 'All Categories',
    'catalog_section.sub_category': 'Sub-category',
    'catalog_section.all_sub_categories': 'All Sub-categories',
    'catalog_section.daily_price': 'Daily Price',
    'catalog_section.apply_filters': 'Apply Filters',

    // blog section
    'blog_section.title': 'Latest Blog Articles',
    'blog_section.description': 'Explore our tips, guides, and updates to succeed in all your DIY projects',
    'blog_section.min': 'min',
    'blog_section.read_article': 'Read Article',
    'blog_section.view_all': 'View all articles',

    // customer reviews
    'customer_reviews.title': 'What our users say',
    'customer_reviews.description': 'Find out what our users think about our platform.',

    // rental process
    'rental_process.title': 'How does it work?',
    'rental_process.description': 'Rent your tools in 4 simple steps...',
    'rental_process.step1.title': 'Post your listing in a few clicks',
    'rental_process.step1.description': 'Add your tools with photos and a detailed description in just a few minutes.',
    'rental_process.step2.title': 'Maximize your visibility',
    'rental_process.step2.description': 'Your listing is seen by thousands of users looking for tools.',
    'rental_process.step3.title': 'Receive your first bookings',
    'rental_process.step3.description': 'Renters contact you directly to reserve your tools for the desired dates.',
    'rental_process.step4.title': 'Collect your earnings with peace of mind',
    'rental_process.step4.description': 'Receive your payments securely and generate additional income.',

    // Profile translations
    'profile.first_name': 'First name',
    'profile.last_name': 'Last name',
    'profile.email': 'Email',
    'profile.phone': 'Phone number',
    'profile.country': 'Country',
    'profile.address': 'Address',
    'profile.edit_profile_photo': 'Click on "Edit" to change your profile photo',
    'profile.verified': 'Verified',
    'profile.account_type_individual': 'Individual',
    'profile.account_type_company': 'Company',
    'profile.average_rating': 'Average rating',
    'profile.rentals_completed': 'Rentals completed',
    'profile.active_ads': 'Active ads',
    'profile.total_earnings': 'Total earnings',
    'profile.delete_account': 'Delete my account',
    'profile.back_home': 'Back to home',
    'profile.profile': 'Profile',
    'profile.favorites': 'Favorites',
    'profile.ads': 'Ads',
    'profile.reservations': 'Reservations',
    'profile.requests': 'Requests',
    'profile.wallet': 'Wallet',
    'profile.edit': 'Edit',
    'profile.member_since': 'Member since {date}',
    'profile.select_country': 'Select a country',
    'profile.address_placeholder': 'Enter your full address',
    'profile.address_hint': 'Enter a valid address compatible with Google Maps',
    'profile.delete_confirm': 'Are you sure you want to delete your account?',
    'profile.delete_description': 'This action is irreversible. All your data, ads, reservations, and transaction history will be permanently deleted.',
    'profile.account_deletion_pending': 'Account pending deletion',

    // Wallet translations
    'wallet.title': 'My Wallet',
    'wallet.total': 'Total',
    'wallet.cumulative_balance': 'Cumulative balance',
    'wallet.available': 'Available',
    'wallet.available_balance': 'Available balance',
    'wallet.successful': 'Successful',
    'wallet.successful_transactions': 'Successful transactions',
    'wallet.withdraw_money': 'Withdraw my money',
    'wallet.withdrawal_note': 'You can withdraw your money once your cumulative balance reaches 20 GBP.',
    'wallet.conversion_rate': '20 GBP = {minWithdrawalEUR} EUR',
    'wallet.dynamic_conversion': 'The conversion rate updates dynamically based on the currency selected in the account.',

    // recent transactions
    'wallet.recent_transactions': 'Recent Transactions',
    'wallet.select_time_period': 'Select a time period',
    'wallet.all_transactions': 'All transactions',
    'wallet.incoming_payments': 'Incoming payments',
    'wallet.withdrawal': 'Withdrawal',
    'wallet.reset': 'Reset',
    'wallet.completed': 'Completed',
    'wallet.pending': 'Pending',
    'wallet.failed': 'Failed',

     // New FAQ translations
    'faq.hero.title': 'Frequently Asked Questions',
    'faq.hero.subtitle': 'Find quick answers to your most common questions',
    'faq.title': 'General Questions',
    'faq.general.q1': 'What is Bricola and how does it work?',
    'faq.general.a1': 'Bricola LTD is a peer-to-peer rental platform for tools and equipment. Users can list their tools for rent or rent tools from others. The platform manages transactions, deposits, and dispute resolution.',
    'faq.general.q2': 'What categories of tools can be listed?',
    'faq.general.a2': 'Currently, Bricola supports DIY, gardening, cleaning, and event-related equipment. More categories may be added based on market needs.',
    'faq.general.q3': 'Is there a mobile app for Bricola?',
    'faq.general.a3': 'Yes. Bricola is available on both iOS and Android, in addition to a full-featured web platform.',
    'faq.general.q4': 'Can I use Bricola from any country?',
    'faq.general.a4': 'Currently, Bricola serves users in the Gulf region. Expansion to other regions is planned.',
    'faq.general.q5': 'Can businesses list tools?',
    'faq.general.a5': 'Yes, but Bricola is primarily designed for individual users. Professional listings must comply with local business regulations.',
    'faq.general.q6': 'What items are prohibited?',
    'faq.general.a6': 'Illegal items, hazardous equipment, or tools that violate safety laws are strictly forbidden.',
    'faq.general.q7': 'Can I suggest a feature?',
    'faq.general.a7': 'Yes, we welcome feedback. Contact support with your idea and we’ll consider it for future updates.',
    'faq.general.q8': 'How do I contact customer support?',
    'faq.general.a8': 'Use the WhatsApp chat, or email us at support@bricolaltd.com. Our team is available 7 days a week.',
    'faq.renters.title': 'For Renters',
    'faq.renters.q1': 'How do I create an account?',
    'faq.renters.a1': 'Register with your name, email, phone number, and verification documents if required. You will need to confirm your phone and email.',
    'faq.renters.q2': 'Why is ID verification required?',
    'faq.renters.a2': 'To ensure trust and security, ID verification may be requested before renting out high-value tools or making large withdrawals.',
    'faq.renters.q3': 'What should I do before receiving a tool?',
    'faq.renters.a3': 'Make sure your ID is verified, agree on rental terms with the owner, and inspect the tool upon handover.',
    'faq.renters.q4': 'What if the tool gets damaged during my rental?',
    'faq.renters.a4': 'Inform the owner and support immediately. You may be asked to provide evidence so the issue can be resolved through the deposit.',
    'faq.owners.title': 'For Owners',
    'faq.owners.q1': 'How do I list a tool?',
    'faq.owners.a1': 'Go to "List a Tool", upload clear photos, provide a description, condition, guarantee, price per day, and select the required deposit.',
    'faq.owners.q2': 'What happens after I list my item?',
    'faq.owners.a2': 'It will be reviewed by our moderation team before going live. You’ll be notified when someone makes a booking.',
    'faq.owners.q3': 'Can I reject a booking request?',
    'faq.owners.a3': 'Yes, owners can accept or reject requests. However, excessive rejections without valid reason may affect your visibility.',
    'faq.owners.q4': 'What should I do before handing over my tool?',
    'faq.owners.a4': 'Check the renter’s ID, document the tool’s condition with photos, and agree on return terms.',
    'faq.owners.q5': 'What if the tool is damaged?',
    'faq.owners.a5': 'Submit evidence within 24 hours of return. Bricola will review and decide whether to compensate from the deposit.',
    'faq.owners.q6': 'Is there insurance for listed tools?',
    'faq.owners.a6': 'Currently, Bricola does not offer insurance. Owners are advised to list only tools they can risk renting.',
    'faq.payment.title': 'Payments & Safety',
    'faq.payment.q1': 'How are payments handled?',
    'faq.payment.a1': 'Payments are processed securely via Stripe. Renters pay in advance, including the deposit.',
    'faq.payment.q2': 'What is the security deposit?',
    'faq.payment.a2': 'A refundable amount held by Stripe to cover potential damages or non-return. It’s automatically released upon successful return.',
    'faq.payment.q3': 'How do I withdraw my earnings?',
    'faq.payment.a3': 'You can request a payout to your bank account via Wise.',
    'faq.payment.q4': 'What fees does Bricola charge?',
    'faq.payment.a4': 'Bricola charges a 15% commission on every successful rental. No listing or monthly fees.',
    'faq.payment.q5': 'How are disputes handled?',
    'faq.payment.a5': 'All disputes are handled by our internal support team within 72 hours. Their decision is final.',
    'faq.payment.q6': 'What measures are in place for safety?',
    'faq.payment.a6': 'ID verification, user reviews, secure payments, and support monitoring ensure a safe and trusted environment.',
    // Navigation
    'nav.home': 'Home',
    'nav.catalog': 'Catalogue',
    'nav.navigation': 'navigation',
    'nav.propos': 'About Us',
    'nav.blog': 'Blog',
    'nav.contact': 'Contact Us',
    'nav.rent': 'Rent',
    'nav.list': 'List a tool',
    'nav.login': 'Login',
    'nav.signup': 'Sign up',
    
    // Hero section
    'hero.title': 'Rent and share your tools with ease',
    'hero.subtitle': 'The platform that connects tool owners with those who need them. Individuals and professionals, find the perfect tool near you.',
    'hero.search.placeholder': 'Search for a tool...',
    'hero.search.location': 'Location',
    'hero.search.button': 'Search',
    'hero.available_tools': 'Tools Available',
    'hero.active_users': 'Active Users',  
    'hero.cities_covered': 'Cities Covered',
    
    // Categories
    'categories.title': 'Our Categories',
    'categories.description': 'Find the perfect tool for your needs',
    'categories.gardening': 'Gardening',
    'categories.cleaning': 'Cleaning',
    'categories.diy': 'DIY',
    'categories.events': 'Event Equipment',
    'categories.transport': 'Transport',
    
    // Tools
    'tools.featured': 'Featured tools',
    'tools.description': 'Top-rated and most requested tools by our community',
    'tools.display_all': 'View All Tools',
    'tools.by': 'by',
    'tools.day': 'day',
    'tools.available': 'Available',
    'tools.rent': 'Rent',
    'tools.details': 'View details',
    'tools.new_ad': 'New ad',
    'tools.my_ads': 'My ads',
    'tools.edit': 'Edit',
    'tools.view': 'View',
    'tools.delete': 'Delete',
    'tools.published': 'Published',
    'tools.unpublished': 'Unpublished',
    'tools.pending': 'Pending',
    'tools.approved': 'Approved',
    'tools.rejected': 'Rejected',
    'tools.back_to_results': 'Back to Results',
    'tools.verified': 'Verified',
    'tools.owner': 'Owner',
    'tools.model': 'Model',
    'tools.brand': 'Brand',
    'tools.year_of_purchase': 'Year of Purchase',
    'tools.fees_and_taxes': 'Including fees and tax',
    'tools.of': 'of',
    'tools.charged': 'charged',
    'tools.deposit': 'Deposit',
    'tools.refunded': '(refunded at the end of rental)',
    'tools.rent_now': 'Rent Now',
    'tools.add_to_favorites': 'Add to Favorites',
    'tools.remove_from_favorites': 'Remove from Favorites',
    'tools.desc': 'Description',
    'tools.instructions': 'Owner\'s Instructions',
    'tools.reviews': 'Renter Reviews',


    // Forms
    'form.first_name': 'First name',
    'form.last_name': 'Last name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.address': 'Address',
    'form.country': 'Country',
    'form.password': 'Password',
    'form.confirm_password': 'Confirm password',
    'form.title': 'Title',
    'form.description': 'Description',
    'form.price': 'Price',
    'form.category': 'Category',
    'form.location': 'Location',
    
    // Actions
    'action.search': 'Search',
    'action.filter': 'Filter',
    'action.sort': 'Sort',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.confirm': 'Confirm',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'action.view': 'View',
    'action.contact': 'Contact',
    'action.close': 'Close',
    'action.back': 'Back',
    'action.next': 'Next',
    'action.previous': 'Previous',
    
    // Floating Action Button
    'fab.contact_support': 'Contact support',
    'fab.publish_ad': 'Publish ad',
    'fab.find_tool': 'Find my tool',
    
    // Messages
    'message.success': 'Success',
    'message.error': 'Error',
    'message.loading': 'Loading...',
    'message.no_results': 'No results found',
    'message.confirm_delete': 'Are you sure you want to delete?',
    
    // Footer
    'footer.about': 'About',
    'footer.help': 'Help',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.rights': 'All rights reserved',
    'footer.cgu': 'Terms',
    'footer.privacy': 'Privacy policy',
    'footer.faq': 'FAQ',
    'footer.description': 'The tool rental platform that connects owners with those who need them. Simple, secure, and local.“www.bricolaltd.com” is a trademark of BRICOLA LTD.Registered in England and Wales under number: 16401372',
    'footer.contrat': 'Rental Agreement', // Added
    'footer.payment': 'Payment Methods', // Added
    'footer.useful_links': 'Useful Links', // Added
    'footer.help_center': 'Help Center', // Added
    'footer.owner_guide': 'Owner’s Guide', // Added
    'footer.renter_guide': 'Renter’s Guide', // Added
    'footer.terms_conditions': 'Terms & Conditions', // Added
    
    // Login
    'login.title': 'Login',
    'login.subtitle': 'Connect to your Bricola LTD account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.signin': 'Sign in',
    'login.no_account': 'No account yet? Sign up',
    'login.forgot_password': 'Forgot password?',

    // Register
    'register.title': 'Sign up',
    'register.subtitle': 'Create your Bricola LTD account',
    'register.user_type': 'User type',
    'register.individual': 'Individual',
    'register.business': 'Business',
    'register.first_name': 'First name',
    'register.last_name': 'Last name',
    'register.phone': 'Phone',
    'register.country': 'Country',
    'register.address': 'Address',
    'register.address_help': 'Complete address with postal code and city',
    'register.password': 'Password',
    'register.confirm_password': 'Confirm password',
    'register.terms': 'I accept the terms of use',
    'register.sales_conditions': 'I accept the terms and conditions and sales conditions',
    'register.create_account': 'Create my account',
    'register.have_account': 'Already have an account? Sign in',
    'register.select_country': 'Select a country',

    // About
    'about.title': 'Welcome to Bricola LTD ',
    'about.subtitle': 'Your trusted platform for peer-to-peer tool rentals across the Gulf region',
    'about.mission_title': 'Our Mission',
    'about.mission_1': 'Bricola LTD was founded in 2025 and is registered in the United Kingdom. The idea was born out of a simple but powerful need: many people own tools they rarely use, while others constantly need access to quality equipment without the burden of buying. Our platform bridges this gap by enabling individuals to rent tools from one another safely, affordably, and efficiently.',
    'about.mission_2': 'We specialize in connecting people who need tools for home improvement, gardening, cleaning, and events with local tool owners. Through our easy-to-use app and website, users can list, search, and rent tools within minutes.',
    'about.mission_3': 'At Bricola, we believe in the power of the sharing economy to reduce waste, encourage sustainability, and empower communities. Our service is secure, transparent, and built with user trust at its core. With a robust digital payment system and built-in security features, Bricola ensures that every transaction is smooth and protected.',
    'about.mission_4': 'By choosing Bricola LTD, you’re not only saving money and time – you’re also joining a smarter, greener way to access what you need. We’re proud to be building the future of tool rental in the Gulf.',
    'about.mission_5': ' Thank you for being part of the Bricola community.',
    'about.values_title': 'Our Values',
    'about.community': 'Community',
    'about.community_desc': 'Create connections between neighbors and promote local mutual aid',
    'about.security': 'Security',
    'about.security_desc': 'Guarantee secure transactions and comprehensive insurance',
    'about.quality': 'Quality',
    'about.quality_desc': 'Ensure all tools meet our quality standards',
    'about.simplicity': 'Simplicity',
    'about.simplicity_desc': 'Make tool rental as simple as a click',
    'about.stats_title': 'Bricola in numbers',
    'about.tools_available': 'Tools available',
    'about.active_users': 'Active users',
    'about.cities_covered': 'Cities covered',
    'about.satisfaction': 'Customer satisfaction',
    'about.team_title': 'Our Team',

    // Contact
    'contact.title': 'Contact us',
    'contact.subtitle': 'A question, a problem or just want to chat? Our team is here to help you.',
    'contact.form_title': 'Send us a message',
    'contact.first_name': 'First name',
    'contact.last_name': 'Last name',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send message',
    'contact.email_title': 'Email',
    'contact.phone_title': 'Phone',
    'contact.address_title': 'Address',
    'contact.hours_title': 'Hours',
    'contact.hours_weekdays': 'Monday - Friday: 9:00 AM - 6:00 PM',
    'contact.hours_saturday': 'Saturday: 10:00 AM - 4:00 PM',
    'contact.hours_sunday': 'Sunday: Closed',
    'contact.faq_title': 'Frequently asked questions',
    'contact.how_to_rent': 'How to rent a tool?',
    'contact.how_to_rent_answer': 'Search for the desired tool, select rental dates, and confirm your reservation. It\'s that simple!',
    'contact.problem': 'What to do in case of a problem?',
    'contact.problem_answer': 'Contact us immediately via our customer support. We are here to solve all your problems quickly.',
    'contact.how_to_list': 'How to list my tools?',
    'contact.how_to_list_answer': 'Click on "List a tool" in the navigation, add details and photos of your tool, and start earning money.',
    'contact.insurance': 'Are tools insured?',
    'contact.insurance_answer': 'Yes, all tools rented via Bricola are covered by our comprehensive insurance for your peace of mind.',

    // Add Tool
    'add_tool.title': 'List a tool',
    'add_tool.subtitle': 'Share your tools with the community and generate income by renting them easily',
    'add_tool.info_title': 'Tool information',
    'add_tool.general_info': 'General information',
    'add_tool.ad_title': 'Ad title',
    'add_tool.brand': 'Brand',
    'add_tool.model': 'Model',
    'add_tool.year': 'Purchase year',
    'add_tool.description': 'Description',
    'add_tool.categorization': 'Categorization',
    'add_tool.category': 'Category',
    'add_tool.subcategory': 'Subcategory',
    'add_tool.condition': 'Tool condition',
    'add_tool.pricing': 'Pricing',
    'add_tool.price_per_day': 'Price per day (€)',
    'add_tool.deposit': 'Deposit (€)',
    'add_tool.location_title': 'Location',
    'add_tool.address': 'Address or city',
    'add_tool.photos_title': 'Photos',
    'add_tool.add_photos': 'Add your photos',
    'add_tool.drop_images': 'Drop your images here or click to browse',
    'add_tool.browse_files': 'Browse files',
    'add_tool.file_format': 'PNG, JPG up to 10MB • 5 photos maximum',
    'add_tool.instructions_title': 'Usage instructions',
    'add_tool.owner_instructions': 'Owner instructions',
    'add_tool.publish': 'Publish ad',
    'add_tool.choose_category': 'Choose a category',
    'add_tool.choose_subcategory': 'Choose a subcategory',
    'add_tool.condition_new': '✨ New',
    'add_tool.condition_excellent': '🌟 Excellent',
    'add_tool.condition_good': '👍 Good',
    'add_tool.condition_fair': '👌 Fair',

    // Categories and subcategories
    'category.gardening': 'Gardening',
    'category.gardening.lawn': 'Lawn',
    'category.gardening.soil': 'Soil',
    'category.gardening.wood': 'Wood',
    'category.gardening.tree': 'Tree',
    'category.gardening.leaves': 'Leaves',

    'category.cleaning': 'Cleaning',
    'category.cleaning.fabric': 'Fabric',
    'category.cleaning.water': 'Water',
    'category.cleaning.dust': 'Dust',

    'category.diy': 'DIY',
    'category.diy.construction': 'Construction',
    'category.diy.electricity': 'Electricity',
    'category.diy.painting': 'Painting',
    'category.diy.screws_and_bolts': 'Screws and bolts',

    'category.transport': 'Transport',
    'category.transport.heavy_load': 'Heavy load',
    'category.transport.engine': 'Engine',
    'category.transport.wheel': 'Wheel',

    'category.event': 'Event',
    'category.event.lighting': 'Lighting',
    'category.event.kitchen': 'Kitchen',
    'category.event.entertainment_and_games': 'Entertainment and games',
    'category.event.furniture': 'Furniture',
    'category.event.decoration': 'Decoration',
    'category.event.structure': 'Structure',

    // Common
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.language': 'Language',
    'common.currency': 'Currency',
    'common.menu': 'Menu',
    'common.navigation': 'Navigation',
    'common.home': 'Home',
  },
  ar: {
    // pagination
    'pagination.next': 'التالي',
    'pagination.previous': 'السابق',

    // catalog section
    'catalog_section.title': 'أداة معثور عليها',
    'catalog_section.category': 'الفئة',
    'catalog_section.sort_by': 'ترتيب حسب',
    'catalog_section.most_recent': 'الأحدث',
    'catalog_section.price_low_to_high': 'السعر: من الأدنى إلى الأعلى',
    'catalog_section.price_high_to_low': 'السعر: من الأعلى إلى الأدنى ',
    'catalog_section.top_rated': 'الأعلى تقييمًا',
    'catalog_section.filters': 'المرشحات',
    'catalog_section.search': 'البحث',
    'catalog_section.tool_name': 'اسم الأداة',
    'catalog_section.location': 'الموقع',
    'catalog_section.all_categories': 'جميع الفئات',
    'catalog_section.sub_category': 'فئة فرعية',
    'catalog_section.all_sub_categories': 'جميع الفئات الفرعية',
    'catalog_section.daily_price': 'السعر اليومي',
    'catalog_section.apply_filters': 'بحث',
    'catalog_section.by': 'بواسطة',
    


    // blog section
    'blog_section.title': 'أحدث مقالات المدونة',
    'blog_section.description': 'اكتشف نصائحنا وأدلتنا وآخر الأخبار لإنجاح جميع مشاريعك في الأشغال اليدوية',
    'blog_section.min': 'دقيقة',
    'blog_section.read_article': 'قراءة المقال',
    'blog_section.view_all': 'عرض جميع المقالات',

     // customer reviews
    'customer_reviews.title': 'آراء عملائنا',
    'customer_reviews.description': 'اكتشف آراء مستخدمينا حول المنصة',

    // rental process
    'rental_process.title': 'كيف يعمل النظام؟',
    'rental_process.description': 'أجر أدواتك في 4 خطوات بسيطة',
    'rental_process.step1.title': 'أنشر إعلانك ببضع نقرات',
    'rental_process.step1.description': 'أضف أدواتك مع الصور والوصف المفصل  في دقائق معدودة.',
    'rental_process.step2.title': 'زد من ظهور إعلانك',
    'rental_process.step2.description': 'إعلانك مرئي لآلاف المستخدمين الباحثين عن الأدوات.',
    'rental_process.step3.title': 'استقبل أولى الحجوزات',
    'rental_process.step3.description': 'يتواصل معك المستأجرون مباشرةً لحجز أدواتك في التواريخ المطلوبة.',
    'rental_process.step4.title': 'احصل على أرباحك بأمان',
    'rental_process.step4.description': 'استلم دفعاتك بأمان وحقق دخلاً إضافياً.',

    // Wallet translations
    'wallet.title': 'محفظتي',
    'wallet.total': 'الإجمالي',
    'wallet.cumulative_balance': 'الرصيد الإجمالي',
    'wallet.available': 'متاح',
    'wallet.available_balance': 'الرصيد المتاح',
    'wallet.successful': 'ناجحة',
    'wallet.successful_transactions': 'المعاملات الناجحة',
    'wallet.withdraw_money': 'سحب أموالي',
    'wallet.withdrawal_note': 'يمكنك سحب أموالك بمجرد أن يصل رصيدك الإجمالي إلى 20 جنيهًا إسترلينيًا.',
    'wallet.conversion_rate': '20 جنيه إسترليني = {minWithdrawalEUR} يورو',
    'wallet.dynamic_conversion': 'يتم تحديث سعر الصرف تلقائيًا حسب العملة المختارة في الحساب.',

    // recent transactions
    'wallet.recent_transactions': 'المعاملات الأخيرة',
    'wallet.select_time_period': 'اختر فترة زمنية',
    'wallet.all_transactions': 'جميع المعاملات',
    'wallet.incoming_payments': 'المدفوعات الواردة',
    'wallet.withdrawal': 'السحب',
    'wallet.reset': 'إعادة تعيين',
    'wallet.completed': 'مكتملة',
    'wallet.pending': 'قيد الانتظار',
    'wallet.failed': 'فشلت',
    
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.catalog': 'الكتالوج',
    'nav.navigation': 'التصفح',
    'nav.propos': 'من نحن',
    'nav.blog': 'المدونة',
    'nav.contact': 'تواصل معنا',
    'nav.rent': 'استئجار',
    'nav.list': 'إضافة أداة',
    'nav.login': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    
    // Hero section
    'hero.title': 'استأجر وشارك أدواتك بسهولة',
    'hero.subtitle': 'المنصة التي تربط أصحاب الأدوات مع من يحتاجونها. أفراد ومحترفون، اعثر على الأداة المثالية بالقرب منك.',
    'hero.search.placeholder': 'البحث عن أداة...',
    'hero.search.location': 'الموقع',
    'hero.search.button': 'بحث',
    'hero.available_tools': 'أداة متاحة',
    'hero.active_users': 'مستخدم نشط',
    'hero.cities_covered': 'مدينة مشمولة',

    // New FAQ translations
    'faq.hero.title': 'الأسئلة الشائعة',
    'faq.hero.subtitle': 'اعثر على إجابات سريعة لأسئلتك الأكثر شيوعًا',
    'faq.title': 'أسئلة عامة',
    'faq.general.q1': 'ما هي Bricola وكيف تعمل؟',
    'faq.general.a1': 'Bricola LTD هي منصة تأجير أدوات ومعدات بين الأفراد. يمكن للمستخدمين عرض أدواتهم للإيجار أو استئجار أدوات من الآخرين. تتولى المنصة إدارة المعاملات، والودائع (التأمينات)، وحل النزاعات.',
    'faq.general.q2': 'ما هي فئات الأدوات التي يمكن عرضها؟',
    'faq.general.a2': 'حاليًا، تدعم Bricola أدوات ومعدات الأعمال اليدوية، والبستنة، والتنظيف، والمناسبات. يمكن إضافة فئات أخرى لاحقًا حسب احتياجات السوق.',
    'faq.general.q3': 'هل يوجد تطبيق مخصص لـ Bricola؟',
    'faq.general.a3': 'نعم، Bricola متاحة على كل من أنظمة iOS وAndroid، بالإضافة إلى منصة ويب شاملة.',
    'faq.general.q4': 'هل يمكنني استخدام Bricola من أي دولة؟',
    'faq.general.a4': 'حاليًا، تقتصر خدمات Bricola على منطقة الخليج، مع وجود خطط للتوسع إلى مناطق أخرى مستقبلًا.',
    'faq.general.q5': 'هل يمكن للشركات عرض أدواتها؟',
    'faq.general.a5': 'نعم، ولكن Bricola مصممة أساسًا للأفراد. يجب على المستخدمين المحترفين الالتزام بالقوانين واللوائح المحلية الخاصة بالأعمال.',
    'faq.general.q6': 'ما هي العناصر الممنوعة؟',
    'faq.general.a6': 'يُمنع تمامًا عرض أو تأجير العناصر غير القانونية، أو المعدات الخطرة، أو الأدوات التي تنتهك قوانين السلامة.',
    'faq.general.q7': 'هل يمكنني اقتراح ميزة جديدة؟',
    'faq.general.a7': 'نعم، نرحب بجميع الاقتراحات. يمكنك التواصل مع الدعم الفني بمقترحك، وسنقوم بدراسته للتحديثات المستقبلية.',
    'faq.general.q8': 'كيف يمكنني التواصل مع خدمة العملاء؟',
    'faq.general.a8': 'يمكنك استخدام دردشة WhatsApp، أو مراسلتنا عبر البريد الإلكتروني: support@bricolaltd.com. فريقنا متاح طوال أيام الأسبوع.',
    'faq.renters.title': 'للمستأجرين',
    'faq.renters.q1': 'كيف أنشئ حسابًا؟',
    'faq.renters.a1': 'سجّل باسمك، وبريدك الإلكتروني، ورقم هاتفك، وقد يُطلب منك تقديم مستندات للتحقق من الهوية. ستحتاج أيضًا إلى تأكيد بريدك الإلكتروني ورقم هاتفك.',
    'faq.renters.q2': 'لماذا يُطلب التحقق من الهوية؟',
    'faq.renters.a2': 'لضمان الأمان والثقة على المنصة، قد يُطلب التحقق من الهوية قبل استئجار أدوات عالية القيمة أو سحب مبالغ كبيرة.',
    'faq.renters.q3': 'ماذا يجب أن أفعل قبل استلام الأداة؟',
    'faq.renters.a3': 'تأكد من التحقق من هويتك، واتفق مع المالك على شروط الإيجار، وافحص الأداة عند استلامها.',
    'faq.renters.q4': 'ماذا لو تعرضت الأداة للتلف أثناء فترة الإيجار؟',
    'faq.renters.a4': 'أخطر المالك وفريق الدعم فورًا. قد يُطلب منك تقديم أدلة لمعالجة المشكلة من خلال مبلغ التأمين.',
    'faq.owners.title': 'لأصحاب الأدوات',
    'faq.owners.q1': 'كيف أعرض أداة للإيجار؟',
    'faq.owners.a1': 'انتقل إلى "عرض أداة"، وقم برفع صور واضحة، وأضف وصفًا للحالة، والضمانات إن وُجدت، وسعر الإيجار اليومي، وحدد مبلغ التأمين المطلوب.',
    'faq.owners.q2': 'ماذا يحدث بعد أن أُدرج أداتي؟',
    'faq.owners.a2': 'سيتم مراجعة الإعلان من قبل فريق الإشراف قبل أن يظهر للمستخدمين. سيتم إشعارك عند قيام أحدهم بالحجز.',
    'faq.owners.q3': 'هل يمكنني رفض طلب الحجز؟',
    'faq.owners.a3': 'نعم، يمكنك قبول أو رفض أي طلب. لكن تكرار الرفض دون أسباب مقنعة قد يؤثر على ظهور أدواتك على المنصة.',
    'faq.owners.q4': 'ماذا يجب أن أفعل قبل تسليم الأداة؟',
    'faq.owners.a4': 'تحقق من هوية المستأجر، وثق حالة الأداة بالصور، واتفق معه على شروط الإرجاع.',
    'faq.owners.q5': 'ماذا أفعل إذا تضررت أداتي؟',
    'faq.owners.a5': 'أرسل الأدلة خلال 24 ساعة من استرجاع الأداة. ستقوم Bricola بمراجعة الحالة وقد تُصدر تعويضًا من مبلغ التأمين.',
    'faq.owners.q6': 'هل توجد تأمينات على الأدوات المعروضة؟',
    'faq.owners.a6': 'حاليًا، لا توفر Bricola تأمينًا. ننصح بعرض الأدوات التي يمكنك تحمل تأجيرها في حال حدوث أي ضرر.',
    'faq.payment.title': 'الدفع والسلامة',
    'faq.payment.q1': 'كيف تتم معالجة عملية الدفع؟',
    'faq.payment.a1': 'تتم جميع الدفعات بأمان من خلال نظام Stripe. يدفع المستأجر مقدمًا، بما في ذلك مبلغ التأمين.',
    'faq.payment.q2': 'ما هو مبلغ التأمين؟',
    'faq.payment.a2': 'هو مبلغ قابل للاسترداد تحتفظ به Stripe لتغطية أي أضرار أو حالات عدم الإرجاع. يُعاد تلقائيًا بعد استرجاع الأداة بنجاح.',
    'faq.payment.q3': 'كيف أسحب أرباحي؟',
    'faq.payment.a3': 'يمكنك طلب تحويل أرباحك إلى حسابك البنكي من خلال خدمة Wise.',
    'faq.payment.q4': 'ما هي الرسوم التي تفرضها Bricola؟',
    'faq.payment.a4': 'تتقاضى Bricola عمولة بنسبة 15% على كل عملية تأجير ناجحة. لا توجد رسوم على الإدراج أو اشتراكات شهرية.',
    'faq.payment.q5': 'كيف يتم التعامل مع النزاعات؟',
    'faq.payment.a5': 'يتم حل جميع النزاعات من خلال فريق الدعم الداخلي خلال 72 ساعة. القرار الصادر يعتبر نهائيًا.',
    'faq.payment.q6': 'ما هي تدابير السلامة المطبقة؟',
    'faq.payment.a6': 'التحقق من الهوية، تقييمات المستخدمين، المدفوعات الآمنة، ومتابعة مستمرة من فريق الدعم لضمان بيئة موثوقة وآمنة.',
    // Categories
    'categories.title': 'الفئات المتوفرة',
    'categories.description':'ابحث عن الأداة المناسبة حسب احتياجك',
    'categories.gardening': 'البستنة',
    'categories.cleaning': 'التنظيف',
    'categories.diy': 'الأشغال  اليدوية',
    'categories.events': 'معدات الحفلات',
    'categories.transport': 'النقل',
    
    // Tools
    'tools.featured': 'الأدوات المميزة',
    'tools.description': 'الأدوات الأعلى تقييماً والأكثر طلباً من مجتمعنا',
    'tools.by': 'بواسطة',
    'tools.display_all': 'عرض جميع الأدوات',
    'tools.day': 'يوم',
    'tools.available': 'متاح',
    'tools.rent': 'استئجار',
    'tools.details': 'عرض التفاصيل',
    'tools.new_ad': 'إعلان جديد',
    'tools.my_ads': 'إعلاناتي',
    'tools.edit': 'تعديل',
    'tools.view': 'عرض',
    'tools.delete': 'حذف',
    'tools.published': 'منشور',
    'tools.unpublished': 'غير منشور',
    'tools.pending': 'في الانتظار',
    'tools.approved': 'مُوافق عليه',
    'tools.rejected': 'مرفوض',
    'tools.back_to_results': 'الرجوع إلى النتائج',
    'tools.verified': 'موثق',
    'tools.owner': 'المؤجر',
    'tools.model': 'لطراز',
    'tools.brand': 'العلامة التجارية',
    'tools.year_of_purchase': 'سنة الشراء',
    'tools.fees_and_taxes':'يشمل الضرائب والرسوم',
    'tools.of': 'من',
    'tools.charged': 'التي يحددها المؤجر',
    'tools.deposit': 'تأمين',
    'tools.refunded': '(يُسترد عند نهاية الإيجار)',
    'tools.rent_now': 'استأجر الآن',
    'tools.add_to_favorites': 'أضف إلى قائمة المفضّلات',
    'tools.remove_from_favorites': 'إزالة من قائمة المفضّلات',
    'tools.desc': 'الوصف',
    'tools.instructions': 'تعليمات المؤجر',
    'tools.reviews': 'تقييمات المستأجرين',

    // Profile translations
    'profile.first_name': 'الاسم',
    'profile.last_name': 'اللقب',
    'profile.email': 'البريد الإلكتروني',
    'profile.phone': 'رقم الهاتف',
    'profile.country': 'البلد',
    'profile.address': 'العنوان',
    'profile.edit_profile_photo': 'انقر على "تعديل" لتغيير صورة ملفك الشخصي',
    'profile.verified': 'موثّق',
    'profile.account_type_individual': 'شخصي',
    'profile.account_type_company': 'شركة',
    'profile.average_rating': 'متوسط التقييم',
    'profile.rentals_completed': 'عمليات الإيجار المنجزة',
    'profile.active_ads': 'الإعلانات المنشورة',
    'profile.total_earnings': 'الأرباح الإجمالية',
    'profile.delete_account': 'حذف حسابي',
    'profile.back_home': 'العودة للرئيسية',
    'profile.profile': 'الملف الشخصي',
    'profile.favorites': 'المفضلة',
    'profile.ads': 'الإعلانات',
    'profile.reservations': 'الحجوزات',
    'profile.requests': 'الطلبات',
    'profile.wallet': 'المحفظة',
    'profile.edit': 'تعديل',
    'profile.member_since': 'عضو منذ {date}',
    'profile.select_country': 'اختر بلداً',
    'profile.address_placeholder': 'أدخل عنوانك الكامل',
    'profile.address_hint': 'أدخل عنوانًا صالحًا متوافقًا مع خرائط Google',
    'profile.delete_confirm': 'هل أنت متأكد من حذف حسابك؟',
    'profile.delete_description': 'هذا الإجراء لا رجعة فيه. سيتم حذف جميع بياناتك، إعلاناتك، حجوزاتك، وسجل معاملاتك نهائيًا.',
    'profile.account_deletion_pending': 'الحساب في انتظار الحذف',
    
    // Forms
    'form.first_name': 'الاسم الأول',
    'form.last_name': 'الاسم الأخير',
    'form.email': 'البريد الإلكتروني',
    'form.phone': 'الهاتف',
    'form.address': 'العنوان',
    'form.country': 'البلد',
    'form.password': 'كلمة المرور',
    'form.confirm_password': 'تأكيد كلمة المرور',
    'form.title': 'العنوان',
    'form.description': 'الوصف',
    'form.price': 'السعر',
    'form.category': 'الفئة',
    'form.location': 'الموقع',
    
    // Actions
    'action.search': 'بحث',
    'action.filter': 'تصفية',
    'action.sort': 'ترتيب',
    'action.save': 'حفظ',
    'action.cancel': 'إلغاء',
    'action.confirm': 'تأكيد',
    'action.delete': 'حذف',
    'action.edit': 'تعديل',
    'action.view': 'عرض',
    'action.contact': 'اتصال',
    'action.close': 'إغلاق',
    'action.back': 'رجوع',
    'action.next': 'التالي',
    'action.previous': 'السابق',
    
    // Floating Action Button
    'fab.contact_support': 'اتصل بالدعم',
    'fab.publish_ad': 'نشر إعلان',
    'fab.find_tool': 'البحث عن أداة',
    
    // Messages
    'message.success': 'نجح',
    'message.error': 'خطأ',
    'message.loading': 'جاري التحميل...',
    'message.no_results': 'لم يتم العثور على نتائج',
    'message.confirm_delete': 'هل أنت متأكد من الحذف؟',
    
    // Footer
    'footer.about': 'حول',
    'footer.help': 'مساعدة',
    'footer.contact': 'اتصال',
    'footer.legal': 'قانوني',
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.cgu': 'الشروط',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.faq': 'الأسئلة الشائعة',
    'footer.description': 'المنصة التي تربط أصحاب الأدوات بمن يحتاجون إليها. بسيطة، آمنة، ومحلية« www.bricolaltd.com » هي علامة تجارية تابعة لشركة « BRICOLA LTD »مسجلة في إنجلترا وويلز تحت الرقم: 16401372',
    'footer.contrat': 'عقد الإيجار', // Added
    'footer.payment': 'وسائل الدفع', // Added
    'footer.useful_links': 'روابط مفيدة', // Added
    'footer.help_center': 'مركز المساعدة', // Added
    'footer.owner_guide': 'دليل المؤجر', // Added
    'footer.renter_guide': 'دليل المستأجر', // Added
    'footer.terms_conditions': 'الشروط والأحكام', // Added
    // Login
    'login.title': 'تسجيل الدخول',
    'login.subtitle': 'اتصل بحسابك في Bricola LTD',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.signin': 'تسجيل الدخول',
    'login.no_account': 'ليس لديك حساب؟ إنشاء حساب',
    'login.forgot_password': 'نسيت كلمة المرور؟',

    // Register
    'register.title': 'إنشاء حساب',
    'register.subtitle': 'أنشئ حسابك في Bricola LTD',
    'register.user_type': 'نوع المستخدم',
    'register.individual': 'فرد',
    'register.business': 'شركة',
    'register.first_name': 'الاسم الأول',
    'register.last_name': 'الاسم الأخير',
    'register.phone': 'الهاتف',
    'register.country': 'البلد',
    'register.address': 'العنوان',
    'register.address_help': 'العنوان الكامل مع الرمز البريدي والمدينة',
    'register.password': 'كلمة المرور',
    'register.confirm_password': 'تأكيد كلمة المرور',
    'register.terms': 'أوافق على شروط الاستخدام',
    'register.sales_conditions': 'أوافق على الشروط والأحكام وشروط البيع',
    'register.create_account': 'إنشاء حسابي',
    'register.have_account': 'لديك حساب بالفعل؟ تسجيل الدخول',
    'register.select_country': 'اختر بلداً',

    // About
    'about.title': 'مرحبًا بكم في Bricola LTD',
    'about.subtitle': ' منصتكم الموثوقة لتأجير الأدوات بين الأفراد في منطقة الخليج',
    'about.mission_title': 'مهمتنا',
    'about.mission_1': 'تأسست شركة Bricola LTD في عام 2025 ومسجلة في المملكة المتحدة. وُلدت فكرتها من حاجة بسيطة لكنها جوهرية: كثير من الأشخاص يمتلكون أدوات نادرًا ما يستخدمونها، بينما يحتاج آخرون إلى أدوات عالية الجودة بشكل متكرر دون الرغبة في شرائها. منصتنا تسد هذه الفجوة من خلال تمكين الأفراد من تأجير الأدوات فيما بينهم بطريقة آمنة، واقتصادية، وفعّالة.',
    'about.mission_2': 'نحن نُخصص خدماتنا لربط الأشخاص الذين يحتاجون أدوات لأعمال الصيانة المنزلية، أو البستنة، أو التنظيف، أو المناسبات، بأصحاب الأدوات المحليين. من خلال تطبيقنا وموقعنا الإلكتروني السهل الاستخدام، يمكن للمستخدمين عرض الأدوات أو البحث عنها وتأجيرها خلال دقائق.',
    'about.mission_3': 'في Bricola، نؤمن بقوة الاقتصاد التشاركي في الحد من الهدر، وتشجيع الاستدامة، وتمكين المجتمعات. خدماتنا آمنة وشفافة، ومبنية على ثقة المستخدمين. ومع نظام دفع رقمي متكامل وميزات أمان مدمجة، تضمن Bricola أن تكون كل معاملة سلسة ومحمية.',
    'about.mission_4': 'عند اختيارك لـ Bricola LTD، فأنت لا توفر المال والوقت فحسب، بل تنضم أيضًا إلى طريقة أذكى وأكثر استدامة للحصول على ما تحتاجه. نفخر بأننا نُسهم في بناء مستقبل تأجير الأدوات في منطقة الخليج.',
    'about.mission_5': 'شكرًا لكونك جزءًا من مجتمع Bricola.',
    'about.values_title': 'قيمنا',
    'about.community': 'المجتمع',
    'about.community_desc': 'إنشاء روابط بين الجيران وتعزيز التعاون المحلي',
    'about.security': 'الأمان',
    'about.security_desc': 'ضمان المعاملات الآمنة والتأمين الشامل',
    'about.quality': 'الجودة',
    'about.quality_desc': 'التأكد من أن جميع الأدوات تلبي معايير الجودة لدينا',
    'about.simplicity': 'البساطة',
    'about.simplicity_desc': 'جعل تأجير الأدوات بسيط كالنقر على زر',
    'about.stats_title': 'Bricola في الأرقام',
    'about.tools_available': 'الأدوات المتاحة',
    'about.active_users': 'المستخدمون النشطون',
    'about.cities_covered': 'المدن المغطاة',
    'about.satisfaction': 'رضا العملاء',
    'about.team_title': 'فريقنا',

    // Contact
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'لديك سؤال أو مشكلة أو تريد التحدث؟ فريقنا هنا لمساعدتك.',
    'contact.form_title': 'أرسل لنا رسالة',
    'contact.first_name': 'الاسم الأول',
    'contact.last_name': 'الاسم الأخير',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال الرسالة',
    'contact.email_title': 'البريد الإلكتروني',
    'contact.phone_title': 'الهاتف',
    'contact.address_title': 'العنوان',
    'contact.hours_title': 'ساعات العمل',
    'contact.hours_weekdays': 'الاثنين - الجمعة: 9:00 صباحاً - 6:00 مساءً',
    'contact.hours_saturday': 'السبت: 10:00 صباحاً - 4:00 مساءً',
    'contact.hours_sunday': 'الأحد: مغلق',
    'contact.faq_title': 'الأسئلة الشائعة',
    'contact.how_to_rent': 'كيفية استئجار أداة؟',
    'contact.how_to_rent_answer': 'ابحث عن الأداة المطلوبة، اختر تواريخ الاستئجار، وأكد حجزك. الأمر بهذه البساطة!',
    'contact.problem': 'ماذا أفعل في حالة وجود مشكلة؟',
    'contact.problem_answer': 'اتصل بنا فوراً عبر دعم العملاء. نحن هنا لحل جميع مشاكلك بسرعة.',
    'contact.how_to_list': 'كيفية عرض أدواتي؟',
    'contact.how_to_list_answer': 'انقر على "عرض أداة" في التنقل، أضف تفاصيل وصور أداتك، وابدأ في كسب المال.',
    'contact.insurance': 'هل الأدوات مؤمنة؟',
    'contact.insurance_answer': 'نعم، جميع الأدوات المستأجرة عبر Bricola مغطاة بتأميننا الشامل لراحة بالك.',

    // Add Tool
    'add_tool.title': 'عرض أداة',
    'add_tool.subtitle': 'شارك أدواتك مع المجتمع واحصل على دخل من تأجيرها بسهولة',
    'add_tool.info_title': 'معلومات الأداة',
    'add_tool.general_info': 'المعلومات العامة',
    'add_tool.ad_title': 'عنوان الإعلان',
    'add_tool.brand': 'العلامة التجارية',
    'add_tool.model': 'الطراز',
    'add_tool.year': 'سنة الشراء',
    'add_tool.description': 'الوصف',
    'add_tool.categorization': 'التصنيف',
    'add_tool.category': 'الفئة',
    'add_tool.subcategory': 'الفئة الفرعية',
    'add_tool.condition': 'حالة الأداة',
    'add_tool.pricing': 'التسعير',
    'add_tool.price_per_day': 'السعر في اليوم (€)',
    'add_tool.deposit': 'التأمين (€)',
    'add_tool.location_title': 'الموقع',
    'add_tool.address': 'العنوان أو المدينة',
    'add_tool.photos_title': 'الصور',
    'add_tool.add_photos': 'أضف صورك',
    'add_tool.drop_images': 'اسحب صورك هنا أو انقر للتصفح',
    'add_tool.browse_files': 'تصفح الملفات',
    'add_tool.file_format': 'PNG، JPG حتى 10MB • 5 صور كحد أقصى',
    'add_tool.instructions_title': 'تعليمات الاستخدام',
    'add_tool.owner_instructions': 'تعليمات المالك',
    'add_tool.publish': 'نشر الإعلان',
    'add_tool.choose_category': 'اختر فئة',
    'add_tool.choose_subcategory': 'اختر فئة فرعية',
    'add_tool.condition_new': '✨ جديد',
    'add_tool.condition_excellent': '🌟 ممتاز',
    'add_tool.condition_good': '👍 جيد',
    'add_tool.condition_fair': '👌 مقبول',

    // Categories and subcategories
    'category.gardening': 'البستنة',
    'category.gardening.lawn': 'العشب',
    'category.gardening.soil': 'التربة',
    'category.gardening.wood': 'الخشب',
    'category.gardening.tree': 'الشجرة',
    'category.gardening.leaves': 'الأوراق',

    'category.cleaning': 'التنظيف',
    'category.cleaning.fabric': 'الأقمشة',
    'category.cleaning.water': 'الماء',
    'category.cleaning.dust': 'الغبار',

    'category.diy': 'الأشغال اليدوية',
    'category.diy.construction': 'البناء',
    'category.diy.electricity': 'الكهرباء',
    'category.diy.painting': 'الطلاء',
    'category.diy.screws_and_bolts': 'البراغي والصواميل',

    'category.transport': 'النقل',
    'category.transport.heavy_load': 'الأحمال الثقيلة',
    'category.transport.engine': 'المحرك',
    'category.transport.wheel': 'العجل',

    'category.event': 'معدات المناسبات',
    'category.event.lighting': 'الإضاءة',
    'category.event.kitchen': 'المطبخ',
    'category.event.entertainment_and_games': 'الترفيه والألعاب',
    'category.event.furniture': 'الأثاث',
    'category.event.decoration': 'الزينة',
    'category.event.structure': 'الهياكل',

    // Common
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.ok': 'موافق',
    'common.language': 'اللغة',
    'common.currency': 'العملة',
    'common.menu': 'القائمة',
    'common.navigation': 'التنقل',
    'common.home': 'الرئيسية'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  // Set document direction for Arabic
  React.useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
